//! etask:doc file b1811c06637d
/**
* @file flags.cpp
*
* @brief bool, both ways
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "flags.hpp"
#include "support/fixtures.hpp"

namespace sys::scalars {
    flags::flags([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void flags::on_execute()
    {
        // Constants; see support/fixtures.hpp.
    }
    etask::core::outcome flags::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // Both values, in that order. A codec that wrote a constant byte - or
        // that widened `bool` to its C++ storage size rather than the one byte
        // the wire format specifies - passes a test that only ever sends `true`.
        namespace fx = support::fixtures;
        return {fx::yes, fx::no};
    }
} // namespace sys::scalars
