//! etask:doc file b589be6f9b6b
/**
* @file plain_int.cpp
*
* @brief the bare `int` alias, distinct from int32 in the schema
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "plain_int.hpp"
#include "support/fixtures.hpp"

namespace sys::scalars {
    plain_int::plain_int([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void plain_int::on_execute()
    {
        // Constants; see support/fixtures.hpp.
    }
    etask::core::outcome plain_int::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // A distinct value from `signed_widths`' int32, even though the schema's
        // `int` and `int32` lower to the same C++ type and the same four bytes.
        // If the two TypeMap entries ever diverge, the host will be told which
        // spelling produced the wrong number rather than that one of them did.
        return {support::fixtures::plain_int};
    }
} // namespace sys::scalars
