//! etask:doc file 17e4d954081b
/**
* @file positional.cpp
*
* @brief the same values again, declared positionally
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "positional.hpp"
#include "support/fixtures.hpp"

namespace sys::scalars {
    positional::positional([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void positional::on_execute()
    {
        // Constants; see support/fixtures.hpp.
    }
    etask::core::outcome positional::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // The task body cannot tell that this shape was declared positionally -
        // `return {...}` is the same statement either way, and that is the point.
        // The two spellings differ only in what the *bindings* call the fields,
        // so returning fixture values the host already knows lets it decode this
        // reply against the same expectation it uses for a named shape and prove
        // the bytes are identical.
        namespace fx = support::fixtures;
        return {fx::u8, fx::i16, fx::u32, fx::f64, fx::yes};
    }
} // namespace sys::scalars
