//! etask:doc file 0ec60c0a8b19
/**
* @file reals.cpp
*
* @brief float and double, at values that are not round
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "reals.hpp"
#include "support/fixtures.hpp"

namespace sys::scalars {
    reals::reals([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void reals::on_execute()
    {
        // Constants; see support/fixtures.hpp.
    }
    etask::core::outcome reals::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // A float and a double side by side, at values neither width can hold
        // exactly for the other. Widening a float to a double on one end of the
        // wire is the plausible mistake here - both are "a real number", and the
        // frame stays a legal length - so the values are picked so that doing it
        // changes the number rather than preserving it.
        namespace fx = support::fixtures;
        return {fx::f32, fx::f64};
    }
} // namespace sys::scalars
