//! etask:doc file 98ce008d36b6
/**
* @file signed_widths.cpp
*
* @brief int8/16/32/64, all negative
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "signed_widths.hpp"
#include "support/fixtures.hpp"

namespace sys::scalars {
    signed_widths::signed_widths([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void signed_widths::on_execute()
    {
        // Constants; see support/fixtures.hpp for why these ones.
    }
    etask::core::outcome signed_widths::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // All four negative. Sign extension is the integer error that survives a
        // correct width - the bytes are right and the number is not - so it can
        // only be caught by a host expecting a signed value, never by comparing
        // frame lengths.
        namespace fx = support::fixtures;
        return {fx::i8, fx::i16, fx::i32, fx::i64};
    }
} // namespace sys::scalars
