//! etask:doc file adcd0040e314
/**
* @file unsigned_widths.cpp
*
* @brief uint8/16/32/64 in one shape, ascending
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "unsigned_widths.hpp"
#include "support/fixtures.hpp"

namespace sys::scalars {
    unsigned_widths::unsigned_widths([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void unsigned_widths::on_execute()
    {
        // Constants, not a measurement: an expectation the firmware computes is
        // not an expectation. See support/fixtures.hpp.
    }
    etask::core::outcome unsigned_widths::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // Ascending widths, so a field read at the wrong size does not just
        // corrupt itself - it shifts everything after it, and the host sees four
        // wrong values instead of one. That is the failure a single-field test
        // cannot produce.
        namespace fx = support::fixtures;
        return {fx::u8, fx::u16, fx::u32, fx::u64};
    }
} // namespace sys::scalars
