//! etask:doc file 06182150eec4
/**
* @file blink.cpp
*
* @brief blink until it has blinked enough
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "blink.hpp"

namespace sys::led {
    blink::blink(std::uint16_t period_ms, std::uint16_t count, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void blink::on_execute()
    {
    }
    bool blink::is_finished()
    {
        // TODO: return true once this task's work is done.
        return true;
    }
    etask::core::outcome blink::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: return the task result values (branch on `reason`).
        return {};
    }
} // namespace sys::led
