//! etask:doc file 3320ec1ae21c
/**
* @file on.cpp
*
* @brief drive the LED to a brightness, now
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "on.hpp"

namespace sys::led {
    on::on(std::uint8_t brightness, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: do the command's work here - this constructor *is* the task.
        // It runs on arrival and the object is destroyed as this returns.
    }
} // namespace sys::led
