//! etask:doc file 21c9948fd5d6
/**
* @file read_brightness.cpp
*
* @brief report the current brightness
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "read_brightness.hpp"

namespace sys::led {
    read_brightness::read_brightness([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void read_brightness::on_execute()
    {
    }
    etask::core::outcome read_brightness::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: return the task result values (branch on `reason`).
        return {};
    }
} // namespace sys::led
