//! etask:doc file d4a94f27dbaf
/**
* @file read_brightness.hpp
*
* @brief report the current brightness
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_LED_READ_BRIGHTNESS_HPP_
#define SYS_LED_READ_BRIGHTNESS_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::led {
    //! etask:doc class 4f8b6037feba
    /**
    * @brief report the current brightness
    *
    * Runs once and replies - the tier for a task whose answer the caller
    * actually wants.
    *
    * A oneshot_task: on_execute() runs once, then on_complete() produces
    * the result. is_finished() is sealed true in the base and is not
    * yours to override. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class read_brightness : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        read_brightness(context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - brightness : std::uint8_t
        *         e.g. `return {brightness};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::led_read_brightness;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        *
        * Empty: this task takes no parameters.
        */
        using params = etools::meta::typelist<>;

        /**
        * @brief Accessor for the `led` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. See `generated/scopes.hpp`.
        */
        static constexpr auto scope = &generated::scopes::led;
    };
} // namespace sys::led
#endif // SYS_LED_READ_BRIGHTNESS_HPP_
