//! etask:doc file f9dfc6b75f69
/**
* @file sample.cpp
*
* @brief one execution step, then answer
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "sample.hpp"

namespace sys::oneshot {
    sample::sample([[maybe_unused]] context& ctx) //! etask:sig
        : _ctx{ctx}
    {
        // Cleared here rather than by the driver, so a trace can never be the
        // residue of the previous scenario's run of this same task.
        _ctx.recorder.reset();
        _ctx.recorder.ran(support::lifecycle::hook::construct);
    }

    void sample::on_execute()
    {
        _ctx.recorder.ran(support::lifecycle::hook::execute);
    }

    etask::core::outcome sample::on_complete(etask::core::completion_reason reason)
    {
        _ctx.recorder.ran(support::lifecycle::hook::complete);

        // `is_finished()` is sealed true on this tier, so the count reported
        // here is the tier's central claim: one on_execute(), however many ticks
        // the manager was given. The host asserts on exactly this.
        return {
            _ctx.recorder.hooks(),
            _ctx.recorder.executions(),
            static_cast<std::uint8_t>(reason),
        };
    }
} // namespace sys::oneshot
