//! etask:doc file a87de64bdffa
/**
* @file sample.hpp
*
* @brief one execution step, then answer
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_ONESHOT_SAMPLE_HPP_
#define SYS_ONESHOT_SAMPLE_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::oneshot {
    //! etask:doc class 18ff2aca98a9
    /**
    * @brief one execution step, then answer
    *
    * Proves the sealed `is_finished()`: exactly one on_execute() runs, no
    * matter how many ticks the manager is given, and on_complete() follows
    * it. `executions` is the assertion - anything but 1 means the tier's
    * central guarantee is broken.
    *
    * A oneshot_task: an instant_task with a return value. The constructor
    * is the whole job - it is finished the moment it exists - and
    * on_complete() produces the result. is_finished() is sealed true in
    * the base and is not yours to override, so on_execute() is never
    * called: it must be defined because polled_task declares it pure, but
    * leave it empty. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class sample : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        sample(context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - hooks : std::uint8_t
        *           - executions : std::uint8_t
        *           - reason : std::uint8_t
        *         e.g. `return {hooks, executions, reason};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::oneshot_sample;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        *
        * Empty: this task takes no parameters.
        */
        using params = etools::meta::typelist<>;

        /**
        * @brief Names the `oneshot` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 2;   // generated::scopes::oneshot
        //! etask:wire end

    private:
        /**
        * @brief The scope's ledger, held so every hook can reach it.
        *
        * A reference rather than a copy: the trace has to outlive the task, or
        * the instant tier - which has nothing but the context to write to -
        * could not be observed at all, and this tier would be measuring
        * something different from that one.
        */
        context& _ctx;
    };
} // namespace sys::oneshot
#endif // SYS_ONESHOT_SAMPLE_HPP_
