//! etask:doc file ac718d3710d8
/**
* @file latch.cpp
*
* @brief hold a stateful record until told otherwise
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "latch.hpp"

namespace sys::hold {
    latch::latch(std::uint16_t ticks, [[maybe_unused]] context& ctx) //! etask:sig
        : _ctx{ctx}, _remaining{ticks}
    {
        _ctx.note_constructed();
    }

    void latch::on_execute()
    {
        // See sys::swarm::salvo::on_execute for why the decrement is guarded.
        if (_remaining > 0) --_remaining;
        ++_ticks_run;
    }

    void latch::on_pause()
    {
        // A real task would release whatever it must not hold while suspended.
        // Here the only thing worth recording is that the hook fired at all: it
        // is the difference between the manager accepting a pause request and
        // the manager actually suspending the task.
        ++_ctx.paused;
    }

    void latch::on_resume()
    {
        ++_ctx.resumed;
    }

    bool latch::is_finished()
    {
        return _remaining == 0;
    }

    etask::core::outcome latch::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        _ctx.note_concluded();
        return {_ticks_run};
    }
} // namespace sys::hold
