//! etask:doc file 705087fbc248
/**
* @file set_thrust.cpp
*
* @brief drive this rotor to a thrust level
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "set_thrust.hpp"

namespace sys::rotors::fr {
    set_thrust::set_thrust(float level, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void set_thrust::on_execute()
    {
    }
    bool set_thrust::is_finished()
    {
        // TODO: return true once this task's work is done.
        return true;
    }
} // namespace sys::rotors::fr
