//! etask:doc file ac6b9bd1e5da
/**
* @file stop.hpp
*
* @brief cut this rotor immediately
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_ROTORS_FR_STOP_HPP_
#define SYS_ROTORS_FR_STOP_HPP_
#include "../../task.hpp"
#include "context.hpp"

namespace sys::rotors::fr {
    //! etask:doc class 13b56e38b4af
    /**
    * @brief cut this rotor immediately
    *
    * An instant_task: a fire-and-forget command. It runs to completion
    * inside the call that delivers it - the constructor is the whole task -
    * and is then destroyed. It occupies no storage, never sees an update()
    * tick, and sends no reply, so it cannot be paused, resumed, or
    * completed. See etask::core::instant_task.
    */
    //! etask:end doc class
    class stop : public instant_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        stop(context& ctx); //! etask:sig

        static constexpr global::task_id uid = global::task_id::rotors_fr_stop;
    };
} // namespace sys::rotors::fr
#endif // SYS_ROTORS_FR_STOP_HPP_
