//! etask:doc file 3bcecc5f1537
/**
* @file echo.hpp
*
* @brief return the argument, and which link asked
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_SHARED_ECHO_HPP_
#define SYS_SHARED_ECHO_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::shared {
    //! etask:doc class 99f5132945c0
    /**
    * @brief return the argument, and which link asked
    *
    * Echoes its argument so the host can tell a genuine reply from a zero-filled one, and reports nothing about the link itself: the task body cannot see which wire carried it, and the host already knows which socket it wrote to. Sameness of the reply across both links is the property under test.
    *
    * A oneshot_task: on_execute() runs once, then on_complete() produces
    * the result. is_finished() is sealed true in the base and is not
    * yours to override. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class echo : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param token TODO: describe `token`.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        echo(std::uint16_t token, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - token : std::uint16_t
        *           - served : std::uint8_t
        *         e.g. `return {token, served};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::shared_echo;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<std::uint16_t>;

        /**
        * @brief Names the `shared` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 3;   // generated::scopes::shared
        //! etask:wire end

    private:
        /// @brief The value to echo, held from construction until the reply.
        std::uint16_t _token;

        /**
        * @brief This scope's context, whose `served` counter the reply reports.
        *
        * A reference, not a copy: the count has to be the subsystem's rather
        * than this invocation's, or it could not show that both links reached
        * the same device.
        */
        context& _ctx;
    };
} // namespace sys::shared
#endif // SYS_SHARED_ECHO_HPP_
