//! etask:doc file 68ef1badfef6
/**
* @file echo.cpp
*
* @brief return the argument, and which link asked
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "echo.hpp"

namespace sys::shared {
    echo::echo(std::uint16_t token, [[maybe_unused]] context& ctx) //! etask:sig
        : _token{token}, _ctx{ctx}
    {
    }

    void echo::on_execute()
    {
        // Deliberately empty. A oneshot_task seals `is_finished` true, and the
        // manager concludes a finished task *before* offering it a tick - so
        // this hook never runs for this tier, and counting here would report
        // zero forever. The count lives in on_complete() for that reason.
    }

    etask::core::outcome echo::on_complete(etask::core::completion_reason reason)
    {
        // Counted only on the path that actually served a request: an aborted
        // one concluded without doing the work, and inflating the count with it
        // would make the host's "both links reached the same device" check pass
        // on traffic that was never answered.
        if (reason != etask::core::completion_reason::finished) return {std::uint16_t{0}, _ctx.served};

        ++_ctx.served;

        // A token of zero is this task's "did not run" value, and the host
        // asserts on it: an aborted request must be distinguishable from a
        // successful echo of whatever the host happened to send, so the abort
        // path above deliberately does not echo the token back.
        return {_token, _ctx.served};
    }
} // namespace sys::shared
