//! etask:doc file 355ed37048ba
/**
* @file reboot.hpp
*
* @brief reboot the controller
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_REBOOT_HPP_
#define SYS_REBOOT_HPP_
#include "task.hpp"
#include "context.hpp"
#include "../generated/scopes.hpp"
#include <etools/meta/typelist.hpp>

namespace sys {
    //! etask:doc class c85da1c497fc
    /**
    * @brief reboot the controller
    *
    * An instant_task: a fire-and-forget command. It runs to completion
    * inside the call that delivers it - the constructor is the whole task -
    * and is then destroyed. It occupies no storage, never sees an update()
    * tick, and sends no reply, so it cannot be paused, resumed, or
    * completed. See etask::core::instant_task.
    */
    //! etask:end doc class
    class reboot : public instant_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        reboot(context& ctx); //! etask:sig

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::reboot;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        *
        * Empty: this task takes no parameters.
        */
        using params = etools::meta::typelist<>;

        /**
        * @brief Names the `the top-level scope` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 0;   // generated::scopes::system
        //! etask:wire end
    };
} // namespace sys
#endif // SYS_REBOOT_HPP_
