//! etask:doc file 3e49b45e2e91
/**
* @file reboot.cpp
*
* @brief reboot the controller
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "reboot.hpp"

namespace sys {
    reboot::reboot([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void reboot::on_start()
    {
    }
    void reboot::on_execute()
    {
    }
    void reboot::on_pause()
    {
    }
    void reboot::on_resume()
    {
    }
    bool reboot::is_finished()
    {
        return true;
    }
} // namespace sys
