//! etask:doc file 355ed37048ba
/**
* @file reboot.hpp
*
* @brief reboot the controller
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_REBOOT_HPP_
#define SYS_REBOOT_HPP_
#include "task.hpp"
#include "context.hpp"

namespace sys {
    //! etask:doc class c85da1c497fc
    /**
    * @brief reboot the controller
    *
    * An instant_task: a fire-and-forget command. It runs to completion
    * inside the call that delivers it - the constructor is the whole task -
    * and is then destroyed. It occupies no storage, never sees an update()
    * tick, and sends no reply, so it cannot be paused, resumed, or
    * completed. See etask::core::instant_task.
    */
    //! etask:end doc class
    class reboot : public instant_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        reboot(context& ctx); //! etask:sig

        static constexpr global::task_id uid = global::task_id::reboot;
    };
} // namespace sys
#endif // SYS_REBOOT_HPP_
