//! etask:doc file 3e49b45e2e91
/**
* @file reboot.cpp
*
* @brief reboot the controller
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "reboot.hpp"

namespace sys {
    reboot::reboot([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: do the command's work here - this constructor *is* the task.
        // It runs on arrival and the object is destroyed as this returns.
    }
} // namespace sys
