//! etask:doc file 18dd72463e16
/**
* @file latch.hpp
*
* @brief hold a stateful record until told otherwise
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_HOLD_LATCH_HPP_
#define SYS_HOLD_LATCH_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::hold {
    //! etask:doc class 0fad947a6cef
    /**
    * @brief hold a stateful record until told otherwise
    *
    * Runs for a fixed number of ticks like the polled tasks, but can be
    * paused - and a paused task keeps its record, which is what makes the
    * stateful budget fill differently from the polled one.
    *
    * A stateful_task: on_execute() runs each tick until is_finished()
    * returns true (or the task is completed externally), then
    * on_complete(). on_pause()/on_resume() bracket a suspension.
    * See etask::core::stateful_task.
    */
    //! etask:end doc class
    class latch : public stateful_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ticks TODO: describe `ticks`.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        latch(std::uint16_t ticks, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Run once when the task is paused.
        *
        * Make the suspended state safe: stop a motor, release a bus, freeze an
        * integrator, save whatever partial progress must not be lost. Pair with
        * on_resume().
        *
        * This task is a stateful_task, which is a claim that it holds something
        * needing exactly this. If there is nothing to write here, it wants to be
        * a polled_task instead - and would stop paying for two vtable slots.
        */
        void on_pause() override;

        /**
        * @brief Run once when a paused task resumes.
        *
        * The mirror of on_pause(): re-acquire or restart whatever it released,
        * reinitialize timers, reload cached state. A task that releases something
        * on pause and never takes it back is a bug.
        */
        void on_resume() override;

        /**
        * @brief Whether the task is done; polled after each on_execute().
        *
        * Return true once there is no work left; the manager then calls
        * on_complete() and removes the task.
        *
        * To finish unconditionally after a single on_execute(), do not write
        * `return true;` here - declare the task an oneshot_task in the schema.
        * That says so plainly and seals it, so a later edit cannot quietly turn
        * the task into something that never finishes.
        *
        * @return true when finished, false to keep running.
        */
        bool is_finished() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - ticks_run : std::uint16_t
        *         e.g. `return {ticks_run};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::hold_latch;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<std::uint16_t>;

        /**
        * @brief Names the `hold` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 2;   // generated::scopes::hold
        //! etask:wire end
    };
} // namespace sys::hold
#endif // SYS_HOLD_LATCH_HPP_
