//! etask:doc file ac718d3710d8
/**
* @file latch.cpp
*
* @brief hold a stateful record until told otherwise
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "latch.hpp"

namespace sys::hold {
    latch::latch(std::uint16_t ticks, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void latch::on_execute()
    {
    }
    void latch::on_pause()
    {
    }
    void latch::on_resume()
    {
    }
    bool latch::is_finished()
    {
        // TODO: return true once this task's work is done.
        return true;
    }
    etask::core::outcome latch::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: return the task result values (branch on `reason`).
        return {};
    }
} // namespace sys::hold
