// SPDX-License-Identifier: MIT
/**
* @file step.cpp
*
* @brief take one step
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "step.hpp"

namespace system::legs::right {
    step::step(float stride, std::uint8_t speed, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void step::on_start()
    {
    }
    void step::on_execute()
    {
    }
    void step::on_pause()
    {
    }
    void step::on_resume()
    {
    }
    bool step::is_finished()
    {
        return true;
    }
    etools::memory::buffer<> step::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: pack and return the task result (branch on `reason`).
        return {};
    }
} // namespace system::legs::right
