//! etask:doc file c43ae6058bd5
/**
* @file salvo.cpp
*
* @brief occupy a polled record for a fixed number of ticks
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "salvo.hpp"

namespace sys::swarm {
    salvo::salvo(std::uint16_t ticks, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void salvo::on_execute()
    {
    }
    bool salvo::is_finished()
    {
        // TODO: return true once this task's work is done.
        return true;
    }
    etask::core::outcome salvo::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: return the task result values (branch on `reason`).
        return {};
    }
} // namespace sys::swarm
