//! etask:doc file c64888027b71
/**
* @file single.cpp
*
* @brief occupy a polled record, one instance only
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "single.hpp"

namespace sys::swarm {
    single::single(std::uint16_t ticks, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void single::on_execute()
    {
    }
    bool single::is_finished()
    {
        // TODO: return true once this task's work is done.
        return true;
    }
    etask::core::outcome single::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: return the task result values (branch on `reason`).
        return {};
    }
} // namespace sys::swarm
