//! etask:doc file 95dfb57dfa58
/**
* @file volley.cpp
*
* @brief occupy a polled record, but only two at a time
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "volley.hpp"

namespace sys::swarm {
    volley::volley(std::uint16_t ticks, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void volley::on_execute()
    {
    }
    bool volley::is_finished()
    {
        // TODO: return true once this task's work is done.
        return true;
    }
    etask::core::outcome volley::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: return the task result values (branch on `reason`).
        return {};
    }
} // namespace sys::swarm
