//! etask:doc file 4738c3e36cf5
/**
* @file reset_counters.cpp
*
* @brief zero the harness's bookkeeping, now
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "reset_counters.hpp"

namespace sys {
    reset_counters::reset_counters([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: do the command's work here - this constructor *is* the task.
        // It runs on arrival and the object is destroyed as this returns.
    }
} // namespace sys
