//! etask:doc file 3a5d763b89da
/**
* @file set_thrust.hpp
*
* @brief drive this rotor to a thrust level
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_ROTORS_RR_SET_THRUST_HPP_
#define SYS_ROTORS_RR_SET_THRUST_HPP_
#include "../../task.hpp"
#include "context.hpp"

namespace sys::rotors::rr {
    //! etask:doc class 7f572993d212
    /**
    * @brief drive this rotor to a thrust level
    *
    * Ramps the ESC toward a normalized thrust in [0, 1] across ticks.
    * Runs alongside the other three rotors, so it declares concurrency.
    *
    * A polled_task: on_execute() runs each tick until is_finished()
    * returns true (or the task is completed externally), then
    * on_complete(). It cannot be paused - that is a stateful_task.
    * See etask::core::polled_task.
    */
    //! etask:end doc class
    class set_thrust : public polled_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param level TODO: describe `level`.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        set_thrust(float level, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Whether the task is done; polled after each on_execute().
        *
        * Return true once there is no work left; the manager then calls
        * on_complete() and removes the task.
        *
        * To finish unconditionally after a single on_execute(), do not write
        * `return true;` here - declare the task an oneshot_task in the schema.
        * That says so plainly and seals it, so a later edit cannot quietly turn
        * the task into something that never finishes.
        *
        * @return true when finished, false to keep running.
        */
        bool is_finished() override;

        static constexpr global::task_id uid = global::task_id::rotors_rr_set_thrust;
    };
} // namespace sys::rotors::rr
#endif // SYS_ROTORS_RR_SET_THRUST_HPP_
