//! etask:doc file d3ccdf5160c4
/**
* @file avalanche.cpp
*
* @brief widths descending 8,4,2,1 then ascending again
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "avalanche.hpp"

namespace sys::mixed {
    avalanche::avalanche(std::uint64_t a, std::uint32_t b, std::uint16_t c, std::uint8_t d, std::uint16_t e, std::uint32_t f, std::uint64_t g, [[maybe_unused]] context& ctx) //! etask:sig
        : _a{a}
        , _b{b}
        , _c{c}
        , _d{d}
        , _e{e}
        , _f{f}
        , _g{g}
    {
        // Nothing else to do: the round trip is the whole task, and
        // holding the arguments is the whole of holding it.
    }
    void avalanche::on_execute()
    {
        // Deliberately empty. A oneshot_task still gets one execute tick, but
        // there is no work to do in it: the round trip is the measurement, and
        // both halves of it already happened - the arguments were unpacked into
        // the constructor, and the result is produced by on_complete(). Doing
        // anything here would only add a step the driver cannot observe.
    }
    etask::core::outcome avalanche::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // `reason` is not branched on. Every declared shape here is the
        // echo, so a forced completion should still report what arrived
        // rather than an empty result the driver could not tell from a
        // zeroed frame.
        return {_a, _b, _c, _d, _e, _f, _g};
    }
} // namespace sys::mixed
