//! etask:doc file b9e4cc3a55d6
/**
* @file odd_pair.hpp
*
* @brief bool, double, bool, float - the two floating widths off-alignment
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_MIXED_ODD_PAIR_HPP_
#define SYS_MIXED_ODD_PAIR_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::mixed {
    //! etask:doc class be78d77b1a20
    /**
    * @brief bool, double, bool, float - the two floating widths off-alignment
    *
    * The floating-point counterpart to `sandwich`. A double starting at
    * offset 1 and a float starting at offset 10 are both misaligned on
    * Xtensa, where an unaligned load of either is a fault rather than a
    * slow read - so a device that reads the payload by casting rather than
    * by copying does not merely disagree, it traps.
    *
    * A oneshot_task: on_execute() runs once, then on_complete() produces
    * the result. is_finished() is sealed true in the base and is not
    * yours to override. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class odd_pair : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param flag The value to echo back unchanged.
        * @param wide The value to echo back unchanged.
        * @param other The value to echo back unchanged.
        * @param narrow The value to echo back unchanged.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        odd_pair(bool flag, double wide, bool other, float narrow, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - flag : bool
        *           - wide : double
        *           - other : bool
        *           - narrow : float
        *         e.g. `return {flag, wide, other, narrow};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::mixed_odd_pair;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<bool, double, bool, float>;

        /**
        * @brief Names the `mixed` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 2;   // generated::scopes::mixed
        //! etask:wire end

    private:
        // Held between the constructor and on_complete() at the exact width
        // the schema declared. Widening any of these - to `int` by promotion,
        // or to `double` by a toolchain that has no real float - would make
        // this task echo a value it never received, which is the drift the
        // whole project is looking for.
        bool _flag;
        double _wide;
        bool _other;
        float _narrow;
    };
} // namespace sys::mixed
#endif // SYS_MIXED_ODD_PAIR_HPP_
