//! etask:doc file cf6393b5de92
/**
* @file odd_pair.cpp
*
* @brief bool, double, bool, float - the two floating widths off-alignment
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "odd_pair.hpp"

namespace sys::mixed {
    odd_pair::odd_pair(bool flag, double wide, bool other, float narrow, [[maybe_unused]] context& ctx) //! etask:sig
        : _flag{flag}
        , _wide{wide}
        , _other{other}
        , _narrow{narrow}
    {
        // Nothing else to do: the round trip is the whole task, and
        // holding the arguments is the whole of holding it.
    }
    void odd_pair::on_execute()
    {
        // Deliberately empty. A oneshot_task still gets one execute tick, but
        // there is no work to do in it: the round trip is the measurement, and
        // both halves of it already happened - the arguments were unpacked into
        // the constructor, and the result is produced by on_complete(). Doing
        // anything here would only add a step the driver cannot observe.
    }
    etask::core::outcome odd_pair::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // `reason` is not branched on. Every declared shape here is the
        // echo, so a forced completion should still report what arrived
        // rather than an empty result the driver could not tell from a
        // zeroed frame.
        return {_flag, _wide, _other, _narrow};
    }
} // namespace sys::mixed
