//! etask:doc file 913713c472fb
/**
* @file sandwich.cpp
*
* @brief uint8, double, uint8 - the canonical padding trap
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "sandwich.hpp"

namespace sys::mixed {
    sandwich::sandwich(std::uint8_t head, double body, std::uint8_t tail, [[maybe_unused]] context& ctx) //! etask:sig
        : _head{head}
        , _body{body}
        , _tail{tail}
    {
        // Nothing else to do: the round trip is the whole task, and
        // holding the arguments is the whole of holding it.
    }
    void sandwich::on_execute()
    {
        // Deliberately empty. A oneshot_task still gets one execute tick, but
        // there is no work to do in it: the round trip is the measurement, and
        // both halves of it already happened - the arguments were unpacked into
        // the constructor, and the result is produced by on_complete(). Doing
        // anything here would only add a step the driver cannot observe.
    }
    etask::core::outcome sandwich::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // `reason` is not branched on. Every declared shape here is the
        // echo, so a forced completion should still report what arrived
        // rather than an empty result the driver could not tell from a
        // zeroed frame.
        return {_head, _body, _tail};
    }
} // namespace sys::mixed
