//! etask:doc file 391fa84f07d7
/**
* @file signed_run.hpp
*
* @brief alternating signed and unsigned at every width
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_MIXED_SIGNED_RUN_HPP_
#define SYS_MIXED_SIGNED_RUN_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::mixed {
    //! etask:doc class 16547ee7ef69
    /**
    * @brief alternating signed and unsigned at every width
    *
    * Sign extension, not padding. Each signed field is driven to its
    * minimum and each unsigned one to its maximum, so a device that
    * promoted through the wrong signedness returns a value with the top
    * half of its bits flipped rather than a near miss.
    *
    * A oneshot_task: an instant_task with a return value. The constructor
    * is the whole job - it is finished the moment it exists - and
    * on_complete() produces the result. is_finished() is sealed true in
    * the base and is not yours to override, so on_execute() is never
    * called: it must be defined because polled_task declares it pure, but
    * leave it empty. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class signed_run : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param a The value to echo back unchanged.
        * @param b The value to echo back unchanged.
        * @param c The value to echo back unchanged.
        * @param d The value to echo back unchanged.
        * @param e The value to echo back unchanged.
        * @param f The value to echo back unchanged.
        * @param g The value to echo back unchanged.
        * @param h The value to echo back unchanged.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        signed_run(std::int8_t a, std::uint8_t b, std::int16_t c, std::uint16_t d, std::int32_t e, std::uint32_t f, std::int64_t g, std::uint64_t h, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - a : std::int8_t
        *           - b : std::uint8_t
        *           - c : std::int16_t
        *           - d : std::uint16_t
        *           - e : std::int32_t
        *           - f : std::uint32_t
        *           - g : std::int64_t
        *           - h : std::uint64_t
        *         e.g. `return {a, b, c, d, e, f, g, h};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::mixed_signed_run;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<std::int8_t, std::uint8_t, std::int16_t, std::uint16_t, std::int32_t, std::uint32_t, std::int64_t, std::uint64_t>;

        /**
        * @brief Names the `mixed` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 2;   // generated::scopes::mixed
        //! etask:wire end

    private:
        // Held between the constructor and on_complete() at the exact width
        // the schema declared. Widening any of these - to `int` by promotion,
        // or to `double` by a toolchain that has no real float - would make
        // this task echo a value it never received, which is the drift the
        // whole project is looking for.
        std::int8_t _a;
        std::uint8_t _b;
        std::int16_t _c;
        std::uint16_t _d;
        std::int32_t _e;
        std::uint32_t _f;
        std::int64_t _g;
        std::uint64_t _h;
    };
} // namespace sys::mixed
#endif // SYS_MIXED_SIGNED_RUN_HPP_
