//! etask:doc file ba21f45e74a5
/**
* @file signed_run.cpp
*
* @brief alternating signed and unsigned at every width
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "signed_run.hpp"

namespace sys::mixed {
    signed_run::signed_run(std::int8_t a, std::uint8_t b, std::int16_t c, std::uint16_t d, std::int32_t e, std::uint32_t f, std::int64_t g, std::uint64_t h, [[maybe_unused]] context& ctx) //! etask:sig
        : _a{a}
        , _b{b}
        , _c{c}
        , _d{d}
        , _e{e}
        , _f{f}
        , _g{g}
        , _h{h}
    {
        // Nothing else to do: the round trip is the whole task, and
        // holding the arguments is the whole of holding it.
    }
    void signed_run::on_execute()
    {
        // Deliberately empty. A oneshot_task still gets one execute tick, but
        // there is no work to do in it: the round trip is the measurement, and
        // both halves of it already happened - the arguments were unpacked into
        // the constructor, and the result is produced by on_complete(). Doing
        // anything here would only add a step the driver cannot observe.
    }
    etask::core::outcome signed_run::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // `reason` is not branched on. Every declared shape here is the
        // echo, so a forced completion should still report what arrived
        // rather than an empty result the driver could not tell from a
        // zeroed frame.
        return {_a, _b, _c, _d, _e, _f, _g, _h};
    }
} // namespace sys::mixed
