//! etask:doc file e75a689d3544
/**
* @file staircase.cpp
*
* @brief widths ascending 1,2,4,8 - every field naturally aligned
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "staircase.hpp"

namespace sys::mixed {
    staircase::staircase(std::uint8_t a, std::uint16_t b, std::uint32_t c, std::uint64_t d, [[maybe_unused]] context& ctx) //! etask:sig
        : _a{a}
        , _b{b}
        , _c{c}
        , _d{d}
    {
        // Nothing else to do: the round trip is the whole task, and
        // holding the arguments is the whole of holding it.
    }
    void staircase::on_execute()
    {
        // Deliberately empty. A oneshot_task still gets one execute tick, but
        // there is no work to do in it: the round trip is the measurement, and
        // both halves of it already happened - the arguments were unpacked into
        // the constructor, and the result is produced by on_complete(). Doing
        // anything here would only add a step the driver cannot observe.
    }
    etask::core::outcome staircase::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // `reason` is not branched on. Every declared shape here is the
        // echo, so a forced completion should still report what arrived
        // rather than an empty result the driver could not tell from a
        // zeroed frame.
        return {_a, _b, _c, _d};
    }
} // namespace sys::mixed
