//! etask:doc file 0747959cf6cb
/**
* @file staircase.hpp
*
* @brief widths ascending 1,2,4,8 - every field naturally aligned
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_MIXED_STAIRCASE_HPP_
#define SYS_MIXED_STAIRCASE_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::mixed {
    //! etask:doc class db4ad8cd076a
    /**
    * @brief widths ascending 1,2,4,8 - every field naturally aligned
    *
    * The control for `avalanche`. Ascending widths are the one ordering
    * where flat and struct layouts coincide, so this passing while
    * `avalanche` fails isolates the fault to padding rather than to width.
    *
    * A oneshot_task: on_execute() runs once, then on_complete() produces
    * the result. is_finished() is sealed true in the base and is not
    * yours to override. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class staircase : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param a The value to echo back unchanged.
        * @param b The value to echo back unchanged.
        * @param c The value to echo back unchanged.
        * @param d The value to echo back unchanged.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        staircase(std::uint8_t a, std::uint16_t b, std::uint32_t c, std::uint64_t d, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - a : std::uint8_t
        *           - b : std::uint16_t
        *           - c : std::uint32_t
        *           - d : std::uint64_t
        *         e.g. `return {a, b, c, d};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::mixed_staircase;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<std::uint8_t, std::uint16_t, std::uint32_t, std::uint64_t>;

        /**
        * @brief Names the `mixed` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 2;   // generated::scopes::mixed
        //! etask:wire end

    private:
        // Held between the constructor and on_complete() at the exact width
        // the schema declared. Widening any of these - to `int` by promotion,
        // or to `double` by a toolchain that has no real float - would make
        // this task echo a value it never received, which is the drift the
        // whole project is looking for.
        std::uint8_t _a;
        std::uint16_t _b;
        std::uint32_t _c;
        std::uint64_t _d;
    };
} // namespace sys::mixed
#endif // SYS_MIXED_STAIRCASE_HPP_
