//! etask:doc file 0845b341043c
/**
* @file step.cpp
*
* @brief take one step
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "step.hpp"

namespace sys::legs::left {
    step::step(float stride, std::uint8_t speed, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void step::on_execute()
    {
    }
    bool step::is_finished()
    {
        // TODO: return true once this task's work is done.
        return true;
    }
    etask::core::outcome step::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: return the task result values (branch on `reason`).
        return {};
    }
} // namespace sys::legs::left
