// SPDX-License-Identifier: MIT
/**
* @file stop.hpp
*
* @brief immediately halt the joint
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#ifndef TASKS_ARM_ELBOW_STOP_HPP_
#define TASKS_ARM_ELBOW_STOP_HPP_
#include "../../task.hpp"
#include "context.hpp"

namespace tasks::arm::elbow {
    class stop : public task {
    public:
        stop(context& ctx); //! etask:sig
        void on_start() override;
        void on_execute() override;
        void on_pause() override;
        void on_resume() override;
        bool is_finished() override;

        static constexpr global::task_id uid = global::task_id::arm_elbow_stop;
    };
} // namespace tasks::arm::elbow
#endif // TASKS_ARM_ELBOW_STOP_HPP_
