// SPDX-License-Identifier: MIT
/**
* @file read_altitude.cpp
*
* @brief read altitude above the launch point
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "read_altitude.hpp"

namespace sys::sensors::baro {
    read_altitude::read_altitude([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void read_altitude::on_start()
    {
    }
    void read_altitude::on_execute()
    {
    }
    void read_altitude::on_pause()
    {
    }
    void read_altitude::on_resume()
    {
    }
    bool read_altitude::is_finished()
    {
        return true;
    }
    etools::memory::buffer<> read_altitude::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: pack and return the task result (branch on `reason`).
        return {};
    }
} // namespace sys::sensors::baro
