//! etask:doc file 8a812e138f16
/**
* @file failsafe.cpp
*
* @brief emergency stop - cut every rotor now
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "failsafe.hpp"

namespace sys {
    failsafe::failsafe([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void failsafe::on_start()
    {
    }
    void failsafe::on_execute()
    {
    }
    void failsafe::on_pause()
    {
    }
    void failsafe::on_resume()
    {
    }
    bool failsafe::is_finished()
    {
        return true;
    }
} // namespace sys
