//! etask:doc file 00b91875d22c
/**
* @file failsafe.hpp
*
* @brief emergency stop - cut every rotor now
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_FAILSAFE_HPP_
#define SYS_FAILSAFE_HPP_
#include "task.hpp"
#include "context.hpp"

namespace sys {
    //! etask:doc class 31d8e37bb451
    /**
    * @brief emergency stop - cut every rotor now
    *
    * The highest-authority task. It receives sys::context (the composition
    * root) and cuts thrust on all four rotors, then holds them off. Because it
    * reaches the whole machine, it is a root-level task - its scope is the system
    * itself, not any single subsystem.
    *
    * An instant_task: a fire-and-forget command. It runs to completion
    * inside the call that delivers it - the constructor is the whole task -
    * and is then destroyed. It occupies no storage, never sees an update()
    * tick, and sends no reply, so it cannot be paused, resumed, or
    * completed. See etask::core::instant_task.
    */
    //! etask:end doc class
    class failsafe : public instant_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        failsafe(context& ctx); //! etask:sig

        static constexpr global::task_id uid = global::task_id::failsafe;
    };
} // namespace sys
#endif // SYS_FAILSAFE_HPP_
