//! etask:doc file 4738c3e36cf5
/**
* @file reset_counters.cpp
*
* @brief zero the harness's bookkeeping, now
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "reset_counters.hpp"

namespace sys {
    reset_counters::reset_counters([[maybe_unused]] context& ctx) //! etask:sig
    {
        // Reaches both scopes, which is the whole reason this is a root-level
        // task: the harness runs each check against a clean slate, and a
        // per-scope reset would leave the two tiers' counters able to disagree
        // about which check they belong to.
        ctx.swarm = swarm::context{};
        ctx.hold = hold::context{};
    }
} // namespace sys
