//! etask:doc file b87e116ddcc2
/**
* @file probe.cpp
*
* @brief take a polled record for exactly one tick
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "probe.hpp"

namespace sys::swarm {
    probe::probe([[maybe_unused]] context& ctx) //! etask:sig
        : _ctx{ctx}
    {
        _ctx.note_constructed();
    }

    void probe::on_execute()
    {
        _served = true;
    }

    etask::core::outcome probe::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        _ctx.note_concluded();
        return {_served};
    }
} // namespace sys::swarm
