//! etask:doc file c43ae6058bd5
/**
* @file salvo.cpp
*
* @brief occupy a polled record for a fixed number of ticks
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "salvo.hpp"

namespace sys::swarm {
    salvo::salvo(std::uint16_t ticks, [[maybe_unused]] context& ctx) //! etask:sig
        : _ctx{ctx}, _remaining{ticks}
    {
        _ctx.note_constructed();
    }

    void salvo::on_execute()
    {
        // Guarded rather than assumed non-zero: the manager checks is_finished()
        // only *after* an execute, so a task registered with ticks == 0 still
        // gets one call. Decrementing unguarded would wrap it to 65535 and turn
        // a task the harness expects to drain immediately into one that never
        // does - the kind of hang that looks like a framework fault.
        if (_remaining > 0) --_remaining;
        ++_ticks_run;
    }

    bool salvo::is_finished()
    {
        return _remaining == 0;
    }

    etask::core::outcome salvo::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // Counted on every path, not just the natural one. A force-completed
        // task releases its record exactly as a finished one does, and a leak
        // check that ignored the forced path would miss the case where it does
        // not.
        _ctx.note_concluded();
        return {_ticks_run};
    }
} // namespace sys::swarm
