//! etask:doc file c64888027b71
/**
* @file single.cpp
*
* @brief occupy a polled record, one instance only
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "single.hpp"

namespace sys::swarm {
    single::single(std::uint16_t ticks, [[maybe_unused]] context& ctx) //! etask:sig
        : _ctx{ctx}, _remaining{ticks}
    {
        _ctx.note_constructed();
    }

    void single::on_execute()
    {
        // See salvo::on_execute for why the decrement is guarded.
        if (_remaining > 0) --_remaining;
        ++_ticks_run;
    }

    bool single::is_finished()
    {
        return _remaining == 0;
    }

    etask::core::outcome single::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        _ctx.note_concluded();
        return {_ticks_run};
    }
} // namespace sys::swarm
