//! etask:doc file 95dfb57dfa58
/**
* @file volley.cpp
*
* @brief occupy a polled record, but only two at a time
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "volley.hpp"

namespace sys::swarm {
    volley::volley(std::uint16_t ticks, [[maybe_unused]] context& ctx) //! etask:sig
        : _ctx{ctx}, _remaining{ticks}
    {
        _ctx.note_constructed();
    }

    void volley::on_execute()
    {
        // See salvo::on_execute for why the decrement is guarded.
        if (_remaining > 0) --_remaining;
        ++_ticks_run;
    }

    bool volley::is_finished()
    {
        return _remaining == 0;
    }

    etask::core::outcome volley::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        _ctx.note_concluded();
        return {_ticks_run};
    }
} // namespace sys::swarm
