//! etask:doc file a8061f3411bd
/**
* @file quench.cpp
*
* @brief cut this probe now
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "quench.hpp"
#include "support/witness.hpp"

namespace sys::mesh::s0::n1::p1 {
    quench::quench([[maybe_unused]] context& ctx) //! etask:sig
    {
        // An instant command's constructor *is* the task. There is no result
        // to return and no reply to send, so reporting to the witness is the
        // only evidence this specific uid ran.
        support::witness::record(
            static_cast<std::uint16_t>(uid), support::phase::ran);
    }
} // namespace sys::mesh::s0::n1::p1
