from typing import List

from schemav2.models.node import Node
from schemav2.models.param import Param
from schemav2.codegen.naming import Naming

# Lifecycle hooks scaffolded by default. on_complete is intentionally omitted:
# its return type (result buffer) belongs to the deferred wiring pass, and users
# add it when a task actually returns data.
_VOID_HOOKS = ("on_start", "on_execute", "on_pause", "on_resume")


class TaskFile:
    """Renders the ``.hpp`` / ``.cpp`` text for a single task node.

    The constructor's parameter list is the only schema-derived line the updater
    later rewrites in place; it is tagged with :data:`Naming.anchor` in both files.
    """

    @staticmethod
    def hpp_params(task: Node) -> str:
        parts = [f"{p.cpp_type} {p.name}" for p in task.params or []]
        if task.injected_scope is not None:
            parts.append(f"{Naming.context_type}& {Naming.context_param}")
        return ", ".join(parts)

    @staticmethod
    def cpp_params(task: Node) -> str:
        # Declared params are meant to be used, so they stay bare; the scope
        # context is optional per task, so it is the [[maybe_unused]] last arg.
        parts = [f"{p.cpp_type} {p.name}" for p in task.params or []]
        if task.injected_scope is not None:
            parts.append(f"[[maybe_unused]] {Naming.context_type}& {Naming.context_param}")
        return ", ".join(parts)

    @staticmethod
    def render_hpp(task: Node) -> str:
        cls = Naming.class_name(task)
        guard = Naming.include_guard(task, "hpp")
        lines: List[str] = []
        lines.append("// SPDX-License-Identifier: MIT")
        lines.extend(TaskFile.__doc_block(task, f"{cls}.hpp"))
        lines.append(f"#ifndef {guard}")
        lines.append(f"#define {guard}")
        lines.append(f'#include "{Naming.base_include(task)}"')
        if task.injected_scope is not None:
            lines.append(f'#include "{Naming.context_include()}"')
        if task.returns:
            lines.append("#include <etools/memory/buffer.hpp>")
        lines.append("")
        lines.append(f"namespace {Naming.namespace(task)} {{")
        lines.append(f"    class {cls} : public task {{")
        lines.append("    public:")
        lines.append(f"        {cls}({TaskFile.hpp_params(task)}); {Naming.anchor}")
        for hook in _VOID_HOOKS:
            lines.append(f"        void {hook}() override;")
        lines.append("        bool is_finished() override;")
        if task.returns:
            lines.append("        etools::memory::buffer<> on_complete(bool interrupted) override;")
        lines.append("")
        lines.append(
            f"        static constexpr global::task_id uid = "
            f"global::task_id::{Naming.uid_symbol(task)};"
        )
        lines.append("    };")
        lines.append(f"}} // namespace {Naming.namespace(task)}")
        lines.append(f"#endif // {guard}")
        return "\n".join(lines) + "\n"

    @staticmethod
    def render_cpp(task: Node) -> str:
        cls = Naming.class_name(task)
        ns = Naming.namespace(task)
        lines: List[str] = []
        lines.append("// SPDX-License-Identifier: MIT")
        lines.extend(TaskFile.__doc_block(task, f"{cls}.cpp"))
        # No include guard: a .cpp is a translation unit, compiled once, not included.
        lines.append(f'#include "{cls}.hpp"')
        lines.append("")
        lines.append(f"namespace {ns} {{")
        lines.append(f"    {cls}::{cls}({TaskFile.cpp_params(task)}) {Naming.anchor}")
        lines.append("    {")
        lines.append("        // TODO: initialize the task from its parameters.")
        lines.append("    }")
        for hook in _VOID_HOOKS:
            lines.append(f"    void {cls}::{hook}()")
            lines.append("    {")
            lines.append("    }")
        lines.append(f"    bool {cls}::is_finished()")
        lines.append("    {")
        lines.append("        return true;")
        lines.append("    }")
        if task.returns:
            lines.append(f"    etools::memory::buffer<> {cls}::on_complete([[maybe_unused]] bool interrupted)")
            lines.append("    {")
            lines.append("        // TODO: pack and return the task result.")
            lines.append("        return {};")
            lines.append("    }")
        lines.append(f"}} // namespace {ns}")
        return "\n".join(lines) + "\n"

    @staticmethod
    def __doc_block(task: Node, file_name: str) -> List[str]:
        brief = task.description or f"{Naming.class_name(task)} task."
        return [
            "/**",
            f"* @file {file_name}",
            "*",
            f"* @brief {brief}",
            "*",
            "* @note Generated by etask. The constructor signature is owned by the",
            "*       generator (tagged with the etask:sig anchor); the bodies are yours.",
            "*/",
        ]
