//! etask:doc file d1491489ce94
/**
* @file classify.cpp
*
* @brief a custom status code keying its own shape
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "classify.hpp"
#include "support/fixtures.hpp"

namespace sys::keyed {
    classify::classify(std::uint8_t branch, [[maybe_unused]] context& ctx) //! etask:sig
        : _branch{branch}
    {
    }
    void classify::on_execute()
    {
        // The branch came in with the request; there is nothing to classify.
    }
    etask::core::outcome classify::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        namespace fx = support::fixtures;

        // Both branches open with the same `label`, so the *only* thing telling a
        // peer whether two more fields follow is the status byte. A reader that
        // fell back to "decode as much as the frame holds" would find the custom
        // branch's twelve extra bytes on the finished branch too - they are the
        // frame's zero-fill - and hand back a confident-looking 0.0.
        if (_branch == 0)
            return {fx::classify_label};

        // 0x71 sits above the task range, so it must survive the same dispatch as
        // a framework-named code without being read as a rejection. The cast is
        // the schema's own spelling for a custom code (see the generated doc
        // block); status_code has no enumerator for a value only this project
        // knows.
        return etask::core::outcome{
                   fx::classify_label, fx::classify_confidence, fx::classify_detail}
            .with_status(static_cast<etask::core::status_code>(0x71));
    }
} // namespace sys::keyed
