//! etask:doc file 480612f4b417
/**
* @file classify.hpp
*
* @brief a custom status code keying its own shape
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_KEYED_CLASSIFY_HPP_
#define SYS_KEYED_CLASSIFY_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::keyed {
    //! etask:doc class 032aa318d410
    /**
    * @brief a custom status code keying its own shape
    *
    * `custom(0x71)` is the schema's escape hatch for a status the framework
    * does not name. It sits above the task range, so it must survive the same
    * "which shape is this" dispatch as a built-in code without being
    * mistaken for a rejection. `branch` chooses between it and the ordinary
    * completion.
    *
    * A oneshot_task: an instant_task with a return value. The constructor
    * is the whole job - it is finished the moment it exists - and
    * on_complete() produces the result. is_finished() is sealed true in
    * the base and is not yours to override, so on_execute() is never
    * called: it must be defined because polled_task declares it pure, but
    * leave it empty. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class classify : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param branch TODO: describe `branch`.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        classify(std::uint8_t branch, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return One of this task's declared result shapes. The status code
        *         the reply carries is what tells the peer which shape it got,
        *         so pick the status *and* the values together:
        *
        *         finished (0x20):
        *           - label : std::uint8_t
        *           `return {label};`  (the default status;
        *           no with_status() needed)
        *
        *         custom(0x71):
        *           - label : std::uint8_t
        *           - confidence : float
        *           - detail : std::int64_t
        *           `return etask::core::outcome{label, confidence, detail}
        *               .with_status(static_cast<etask::core::status_code>(0x71));`
        *
        *         Returning values with no status keeps the manager's own code
        *         (task_finished / task_aborted). A shape not listed here is not
        *         in the schema, so no peer knows how to decode it.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::keyed_classify;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<std::uint8_t>;

        /**
        * @brief Names the `keyed` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 4;   // generated::scopes::keyed
        //! etask:wire end

    private:
        /**
        * @brief Which of the two shapes the caller asked for.
        *
        * Held from construction to completion: `on_complete` sees only the
        * completion reason, and both of this task's branches are natural
        * completions, so the reason cannot tell them apart.
        */
        std::uint8_t _branch;
    };
} // namespace sys::keyed
#endif // SYS_KEYED_CLASSIFY_HPP_
