//! etask:doc file 10cfcaa6c1f8
/**
* @file converge.hpp
*
* @brief the aborted branch, reachable only by force-completing
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_KEYED_CONVERGE_HPP_
#define SYS_KEYED_CONVERGE_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::keyed {
    //! etask:doc class 405161970ac4
    /**
    * @brief the aborted branch, reachable only by force-completing
    *
    * A polled task that never finishes on its own. Its `finished` branch is
    * therefore unreachable from the wire; the branch a peer can actually
    * provoke is `aborted`, by force-completing the task - which is the shape
    * that reports where it had got to. Declared with different widths on
    * purpose, so an abort that decoded as `finished` would be caught by
    * length rather than by luck.
    *
    * A polled_task: on_execute() runs each tick until is_finished()
    * returns true (or the task is completed externally), then
    * on_complete(). It cannot be paused - that is a stateful_task.
    * See etask::core::polled_task.
    */
    //! etask:end doc class
    class converge : public polled_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param target TODO: describe `target`.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        converge(std::int32_t target, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Whether the task is done; polled after each on_execute().
        *
        * Return true once there is no work left; the manager then calls
        * on_complete() and removes the task.
        *
        * To finish unconditionally after a single on_execute(), do not write
        * `return true;` here - declare the task an oneshot_task in the schema.
        * That says so plainly and seals it, so a later edit cannot quietly turn
        * the task into something that never finishes.
        *
        * @return true when finished, false to keep running.
        */
        bool is_finished() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return One of this task's declared result shapes. The status code
        *         the reply carries is what tells the peer which shape it got,
        *         so pick the status *and* the values together:
        *
        *         finished (0x20):
        *           - iterations : std::uint32_t
        *           `return {iterations};`  (the default status;
        *           no with_status() needed)
        *
        *         aborted (0x21):
        *           - last : std::int32_t
        *           - iterations : std::uint32_t
        *           - settled : bool
        *           `return etask::core::outcome{last, iterations, settled}
        *               .with_status(etask::core::status_code::task_aborted);`
        *
        *         Returning values with no status keeps the manager's own code
        *         (task_finished / task_aborted). A shape not listed here is not
        *         in the schema, so no peer knows how to decode it.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::keyed_converge;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<std::int32_t>;

        /**
        * @brief Names the `keyed` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 4;   // generated::scopes::keyed
        //! etask:wire end

    private:
        /**
        * @brief The value the task reports as where it had got to.
        *
        * Taken from the request rather than computed, so the host knows what it
        * should come back as: the `aborted` branch's whole job here is to prove
        * a *different* shape than `finished` reaches the peer, and it can only do
        * that against a predictable value.
        */
        std::int32_t _target;
    };
} // namespace sys::keyed
#endif // SYS_KEYED_CONVERGE_HPP_
