//! etask:doc file 6ba1400269fc
/**
* @file converge.cpp
*
* @brief the aborted branch, reachable only by force-completing
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "converge.hpp"
#include "support/fixtures.hpp"

namespace sys::keyed {
    converge::converge(std::int32_t target, [[maybe_unused]] context& ctx) //! etask:sig
        : _target{target}
    {
    }
    void converge::on_execute()
    {
        // Deliberately does nothing but stay alive. This task exists to be
        // force-completed, so it must still be running when the abort arrives.
    }
    bool converge::is_finished()
    {
        // Never, on its own. The `finished` branch is therefore unreachable from
        // the wire, and `aborted` is the shape a peer can actually provoke - which
        // is the case under test: a status the *manager* chose, rather than one
        // the task named, still has to select the right shape.
        //
        // A task that never finishes would be a bug in production code and is the
        // point here; the manager reclaims its slot when the abort completes it.
        return false;
    }
    etask::core::outcome converge::on_complete(etask::core::completion_reason reason)
    {
        namespace fx = support::fixtures;

        // Branch on the reason rather than on a parameter, because that is what
        // distinguishes these two shapes in the first place: nothing the requester
        // sent decides it, only how the task ended.
        //
        // The abort branch carries no with_status(). The manager's own
        // task_aborted is already the status the schema keyed this shape to, and
        // naming it again would test the override path instead of the plain one -
        // the plain one being the case a peer meets far more often.
        if (reason == etask::core::completion_reason::finished)
            return {fx::converge_iterations};
        return {_target, fx::converge_iterations, fx::converge_settled};
    }
} // namespace sys::keyed
