//! etask:doc file 74773c2b917e
/**
* @file measure.cpp
*
* @brief three branches, from eighteen bytes down to zero
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "measure.hpp"
#include "support/fixtures.hpp"

namespace sys::keyed {
    measure::measure(std::uint8_t branch, [[maybe_unused]] context& ctx) //! etask:sig
        : _branch{branch}
    {
    }
    void measure::on_execute()
    {
        // The branch was decided by the request; there is no work to do before
        // reporting it.
    }
    etask::core::outcome measure::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // Each branch is reachable on demand, which is the only way to test the
        // narrow ones. A task that picked its shape from real conditions would
        // exercise whichever branch the hardware happened to produce, and the
        // other two would be dead code that still compiled.
        namespace fx = support::fixtures;
        switch (_branch) {
            case 0:
                // The widest branch, and the default status - no with_status(),
                // so the manager's task_finished stands.
                return {fx::measure_value, fx::measure_variance, fx::measure_samples};
            case 1:
                // One byte where the finished branch had eighteen. The frame is
                // the same size either way, so the seventeen bytes after this one
                // are the zero-fill `reply::make` left - a peer reading by length
                // would take them for values.
                return etask::core::outcome{fx::measure_bus}
                    .with_status(etask::core::status_code::task_io_error);
            default:
                // No values at all. Only the status byte distinguishes this from
                // an all-zero reading on the finished branch, which is exactly
                // the confusion the status byte exists to prevent.
                return etask::core::outcome{}
                    .with_status(etask::core::status_code::task_timeout);
        }
    }
} // namespace sys::keyed
