//! etask:doc file 140dc318774b
/**
* @file measure.hpp
*
* @brief three branches, from eighteen bytes down to zero
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_KEYED_MEASURE_HPP_
#define SYS_KEYED_MEASURE_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::keyed {
    //! etask:doc class 454501458861
    /**
    * @brief three branches, from eighteen bytes down to zero
    *
    * `branch` selects which status the task reports, and therefore which
    * shape comes back:
    *
    *   0 -> finished       (double + double + uint16, 18 bytes)
    *   1 -> task_io_error  (uint8, 1 byte)
    *   2 -> task_timeout   ()   - the empty branch
    *
    * The empty branch is the interesting one. The reply frame is sized for
    * the eighteen-byte branch, so on the timeout branch there are seventeen
    * spare bytes after the status - already zeroed by `reply::make`. A peer
    * that decoded by frame length rather than by status would read them as
    * values and see a plausible all-zero reading, which is precisely the
    * silent failure the status byte exists to prevent.
    *
    * A oneshot_task: an instant_task with a return value. The constructor
    * is the whole job - it is finished the moment it exists - and
    * on_complete() produces the result. is_finished() is sealed true in
    * the base and is not yours to override, so on_execute() is never
    * called: it must be defined because polled_task declares it pure, but
    * leave it empty. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class measure : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param branch TODO: describe `branch`.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        measure(std::uint8_t branch, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return One of this task's declared result shapes. The status code
        *         the reply carries is what tells the peer which shape it got,
        *         so pick the status *and* the values together:
        *
        *         finished (0x20):
        *           - value : double
        *           - variance : double
        *           - samples : std::uint16_t
        *           `return {value, variance, samples};`  (the default status;
        *           no with_status() needed)
        *
        *         task_timeout (0x22):
        *           `return etask::core::outcome{}
        *               .with_status(etask::core::status_code::task_timeout);`
        *
        *         task_io_error (0x23):
        *           - bus : std::uint8_t
        *           `return etask::core::outcome{bus}
        *               .with_status(etask::core::status_code::task_io_error);`
        *
        *         Returning values with no status keeps the manager's own code
        *         (task_finished / task_aborted). A shape not listed here is not
        *         in the schema, so no peer knows how to decode it.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::keyed_measure;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<std::uint8_t>;

        /**
        * @brief Names the `keyed` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 4;   // generated::scopes::keyed
        //! etask:wire end

    private:
        /**
        * @brief Which of the three shapes the caller asked for.
        *
        * Held from construction to completion because `on_complete` is handed
        * only a completion reason - the branch selector has to survive the tick
        * in between.
        */
        std::uint8_t _branch;
    };
} // namespace sys::keyed
#endif // SYS_KEYED_MEASURE_HPP_
