//! etask:doc file dfcd72c99a00
/**
* @file hold.cpp
*
* @brief hold this probe, suspendably
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "hold.hpp"
#include "support/witness.hpp"

namespace sys::mesh::s2::n0::p2 {
    hold::hold([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void hold::on_execute()
    {
    }
    void hold::on_pause()
    {
    }
    void hold::on_resume()
    {
    }
    bool hold::is_finished()
    {
        // Nothing here models real work - the tier is what is being
        // exercised, not the duration - so one tick is the whole task.
        return true;
    }
    etask::core::outcome hold::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // Identity, not a measurement: `uid` is this class's own
        // `global::task_id`, fixed at compile time from its schema path. A task
        // running under another's registration would report that other number.
        const auto self = static_cast<std::uint16_t>(uid);
        support::witness::record(self, support::phase::completed);
        return {self};
    }
} // namespace sys::mesh::s2::n0::p2
