// SPDX-License-Identifier: MIT
/**
* @file failsafe.cpp
*
* @brief emergency stop - cut every rotor now
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "failsafe.hpp"

namespace system {
    failsafe::failsafe([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void failsafe::on_start()
    {
    }
    void failsafe::on_execute()
    {
    }
    void failsafe::on_pause()
    {
    }
    void failsafe::on_resume()
    {
    }
    bool failsafe::is_finished()
    {
        return true;
    }
} // namespace system
