//! etask:doc file 3c0a0c881d71
/**
* @file acknowledge.hpp
*
* @brief complete naturally, carrying no result
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_NOTHING_ACKNOWLEDGE_HPP_
#define SYS_NOTHING_ACKNOWLEDGE_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etools/meta/typelist.hpp>

namespace sys::nothing {
    //! etask:doc class f1da22d1c959
    /**
    * @brief complete naturally, carrying no result
    *
    * Declares no `returns:`, so the generator writes no on_complete override
    * and the manager's own task_finished stands. The peer must still get a
    * reply frame.
    *
    * A oneshot_task: on_execute() runs once, then on_complete() produces
    * the result. is_finished() is sealed true in the base and is not
    * yours to override. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class acknowledge : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        acknowledge(context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::nothing_acknowledge;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        *
        * Empty: this task takes no parameters.
        */
        using params = etools::meta::typelist<>;

        /**
        * @brief Names the `nothing` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 1;   // generated::scopes::nothing
        //! etask:wire end
    };
} // namespace sys::nothing
#endif // SYS_NOTHING_ACKNOWLEDGE_HPP_
