//! etask:doc file 3f1911db42ac
/**
* @file acknowledge.cpp
*
* @brief complete naturally, carrying no result
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "acknowledge.hpp"

namespace sys::nothing {
    acknowledge::acknowledge([[maybe_unused]] context& ctx) //! etask:sig
    {
    }
    void acknowledge::on_execute()
    {
        // Nothing to do, and that is the case under test: the task declares no
        // `returns:`, so the generator wrote no on_complete override and the
        // manager's own task_finished is what reaches the peer. What is being
        // proven is that a reply frame goes out at all - an empty result is the
        // one shape whose absence and whose correctness look identical from the
        // payload, so only the arrival of the frame distinguishes them.
    }
} // namespace sys::nothing
