//! etask:doc file b267224bf8ef
/**
* @file report_status.hpp
*
* @brief complete with a chosen status and no result
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_NOTHING_REPORT_STATUS_HPP_
#define SYS_NOTHING_REPORT_STATUS_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::nothing {
    //! etask:doc class a6707487b719
    /**
    * @brief complete with a chosen status and no result
    *
    * Returns nothing but *names* a status, which is the combination that
    * separates "no shape declared" from "no values in this shape". The
    * declared shape is empty, so the result region stays empty while the
    * status byte moves.
    *
    * A oneshot_task: on_execute() runs once, then on_complete() produces
    * the result. is_finished() is sealed true in the base and is not
    * yours to override. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class report_status : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param code TODO: describe `code`.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        report_status(std::uint8_t code, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return One of this task's declared result shapes. The status code
        *         the reply carries is what tells the peer which shape it got,
        *         so pick the status *and* the values together:
        *
        *         task_timeout (0x22):
        *           `return etask::core::outcome{}
        *               .with_status(etask::core::status_code::task_timeout);`
        *
        *         task_io_error (0x23):
        *           `return etask::core::outcome{}
        *               .with_status(etask::core::status_code::task_io_error);`
        *
        *         Returning values with no status keeps the manager's own code
        *         (task_finished / task_aborted). A shape not listed here is not
        *         in the schema, so no peer knows how to decode it.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::nothing_report_status;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<std::uint8_t>;

        /**
        * @brief Names the `nothing` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 1;   // generated::scopes::nothing
        //! etask:wire end

    private:
        /**
        * @brief Which branch the request asked for, held until on_complete.
        *
        * The parameter arrives at construction but is not read until the task
        * concludes, so it has to be kept: `on_complete` is handed a completion
        * reason and nothing else.
        */
        std::uint8_t _code;
    };
} // namespace sys::nothing
#endif // SYS_NOTHING_REPORT_STATUS_HPP_
