//! etask:doc file 54d28c51fc5e
/**
* @file report_status.cpp
*
* @brief complete with a chosen status and no result
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "report_status.hpp"

namespace sys::nothing {
    report_status::report_status(std::uint8_t code, [[maybe_unused]] context& ctx) //! etask:sig
        : _code{code}
    {
    }
    void report_status::on_execute()
    {
        // The whole task is its answer; there is no work to slice.
    }
    etask::core::outcome report_status::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // Both shapes are empty, so the *only* thing that differs between them is
        // the status byte. That is what makes this task worth having: it isolates
        // the discriminator from the values it usually travels with, so a peer
        // that got the shape right by reading the payload length rather than the
        // status has nothing to read here.
        //
        // Anything that is not the io-error branch reports the timeout, rather
        // than the two branches sharing a default. A request naming an
        // out-of-range branch is a broken test, and it should fail against a
        // definite expectation instead of landing on whichever branch happened to
        // be written first.
        if (_code == 0)
            return etask::core::outcome{}
                .with_status(etask::core::status_code::task_io_error);
        return etask::core::outcome{}
            .with_status(etask::core::status_code::task_timeout);
    }
} // namespace sys::nothing
