//! etask:doc file 290bef9114f9
/**
* @file read.cpp
*
* @brief sample the accelerometer
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "read.hpp"

namespace sys::head::imu {
    read::read([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void read::on_execute()
    {
    }
    etask::core::outcome read::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: return the task result values (branch on `reason`).
        return {};
    }
} // namespace sys::head::imu
