//! etask:doc file 9666d118fe3d
/**
* @file blink.cpp
*
* @brief toggle the status LED
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "blink.hpp"

namespace sys {
    blink::blink([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void blink::on_start()
    {
    }
    void blink::on_execute()
    {
    }
    void blink::on_pause()
    {
    }
    void blink::on_resume()
    {
    }
    bool blink::is_finished()
    {
        return true;
    }
} // namespace sys
