// SPDX-License-Identifier: MIT
/**
* @file blink.cpp
*
* @brief toggle the status LED
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "blink.hpp"

namespace sys {
    blink::blink([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void blink::on_start()
    {
    }
    void blink::on_execute()
    {
    }
    void blink::on_pause()
    {
    }
    void blink::on_resume()
    {
    }
    bool blink::is_finished()
    {
        return true;
    }
} // namespace sys
