//! etask:doc file 5bddc90c57c9
/**
* @file blink.hpp
*
* @brief toggle the status LED
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_BLINK_HPP_
#define SYS_BLINK_HPP_
#include "task.hpp"
#include "context.hpp"
#include "../generated/scopes.hpp"
#include <etools/meta/typelist.hpp>

namespace sys {
    //! etask:doc class 3892df1f8e25
    /**
    * @brief toggle the status LED
    *
    * Flips the on-board status LED. A oneshot_task: it toggles once in
    * on_execute() and concludes there.
    *
    * A oneshot_task: on_execute() runs once, then on_complete() produces
    * the result. is_finished() is sealed true in the base and is not
    * yours to override. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class blink : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        blink(context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::blink;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        *
        * Empty: this task takes no parameters.
        */
        using params = etools::meta::typelist<>;

        /**
        * @brief Accessor for the `the top-level scope` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. See `generated/scopes.hpp`.
        */
        static constexpr auto scope = &generated::scopes::system;
    };
} // namespace sys
#endif // SYS_BLINK_HPP_
