// SPDX-License-Identifier: MIT
/**
* @file set_thrust.cpp
*
* @brief drive this rotor to a thrust level
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "set_thrust.hpp"

namespace system::rotors::fl {
    set_thrust::set_thrust(float level, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void set_thrust::on_start()
    {
    }
    void set_thrust::on_execute()
    {
    }
    void set_thrust::on_pause()
    {
    }
    void set_thrust::on_resume()
    {
    }
    bool set_thrust::is_finished()
    {
        return true;
    }
} // namespace system::rotors::fl
