// SPDX-License-Identifier: MIT
/**
* @file stop.cpp
*
* @brief cut this rotor immediately
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "stop.hpp"

namespace system::rotors::fl {
    stop::stop([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void stop::on_start()
    {
    }
    void stop::on_execute()
    {
    }
    void stop::on_pause()
    {
    }
    void stop::on_resume()
    {
    }
    bool stop::is_finished()
    {
        return true;
    }
} // namespace system::rotors::fl
