//! etask:doc file 125e5530b9d8
/**
* @file quench.hpp
*
* @brief cut this probe now
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_MESH_S4_N0_P1_QUENCH_HPP_
#define SYS_MESH_S4_N0_P1_QUENCH_HPP_
#include "../../../../task.hpp"
#include "context.hpp"
#include "../../../../../generated/scopes.hpp"
#include <etools/meta/typelist.hpp>

namespace sys::mesh::s4::n0::p1 {
    //! etask:doc class e2da8983d7c4
    /**
    * @brief cut this probe now
    *
    * An instant command: no result shape, since it has no
    * on_complete and sends no reply. It is here so the fan-out
    * populates all four tiers, and so the instant dispatcher
    * also sees 72 distinct uids.
    *
    * An instant_task: a fire-and-forget command. It runs to completion
    * inside the call that delivers it - the constructor is the whole task -
    * and is then destroyed. It occupies no storage, never sees an update()
    * tick, and sends no reply, so it cannot be paused, resumed, or
    * completed. See etask::core::instant_task.
    */
    //! etask:end doc class
    class quench : public instant_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        quench(context& ctx); //! etask:sig

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::mesh_s4_n0_p1_quench;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        *
        * Empty: this task takes no parameters.
        */
        using params = etools::meta::typelist<>;

        /**
        * @brief Names the `mesh.s4.n0.p1` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 73;   // generated::scopes::mesh_s4_n0_p1
        //! etask:wire end
    };
} // namespace sys::mesh::s4::n0::p1
#endif // SYS_MESH_S4_N0_P1_QUENCH_HPP_
