//! etask:doc file 1bfc42dd480d
/**
* @file transfer.hpp
*
* @brief accept a wide payload and answer with a wide one
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_BULK_TRANSFER_HPP_
#define SYS_BULK_TRANSFER_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::bulk {
    //! etask:doc class f1c1672b8a64
    /**
    * @brief accept a wide payload and answer with a wide one
    *
    * The parameters are eight distinct scalars rather than one large one so that a serializer that mis-packs a *field* - rather than merely mis-sizing the frame - shows up as a wrong value in the reply instead of as a length error.
    *
    * A oneshot_task: on_execute() runs once, then on_complete() produces
    * the result. is_finished() is sealed true in the base and is not
    * yours to override. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class transfer : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param a TODO: describe `a`.
        * @param b TODO: describe `b`.
        * @param c TODO: describe `c`.
        * @param d TODO: describe `d`.
        * @param e TODO: describe `e`.
        * @param f TODO: describe `f`.
        * @param g TODO: describe `g`.
        * @param h TODO: describe `h`.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        transfer(std::uint32_t a, std::uint32_t b, std::uint32_t c, std::uint32_t d, std::uint32_t e, std::uint32_t f, std::uint32_t g, std::uint32_t h, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - sum : std::uint64_t
        *           - count : std::uint32_t
        *           - first : std::uint32_t
        *           - last : std::uint32_t
        *         e.g. `return {sum, count, first, last};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::bulk_transfer;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t>;

        /**
        * @brief Names the `bulk` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 1;   // generated::scopes::bulk
        //! etask:wire end

    private:
        /// @brief The sum of all eight arguments, widened so it cannot wrap.
        std::uint64_t _sum{0};

        /**
        * @brief The first and last arguments, kept verbatim.
        *
        * The sum alone would not localise a fault: it is invariant under a
        * reordering of the parameter list, so a serializer that packed the
        * eight fields backwards would still produce the expected total. The
        * two end values pin the order down.
        */
        std::uint32_t _first;
        std::uint32_t _last;
    };
} // namespace sys::bulk
#endif // SYS_BULK_TRANSFER_HPP_
