//! etask:doc file 7fff93bd4e15
/**
* @file transfer.cpp
*
* @brief accept a wide payload and answer with a wide one
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "transfer.hpp"

namespace sys::bulk {
    transfer::transfer(std::uint32_t a, std::uint32_t b, std::uint32_t c, std::uint32_t d, std::uint32_t e, std::uint32_t f, std::uint32_t g, std::uint32_t h, [[maybe_unused]] context& ctx) //! etask:sig
        : _first{a}, _last{h}
    {
        // Widened before summing: eight uint32 arguments can exceed 32 bits
        // between them, and a sum that wrapped would still look plausible to the
        // host, which is exactly the failure this task exists to expose.
        _sum = static_cast<std::uint64_t>(a) + b + c + d + e + f + g + h;
    }

    void transfer::on_execute()
    {
    }

    etask::core::outcome transfer::on_complete(etask::core::completion_reason reason)
    {
        // `count` is the fixed arity of this task's parameter list, returned so
        // the host can tell a correctly unpacked request from one where the
        // deserializer silently stopped short and zero-filled the remainder -
        // a truncated frame would otherwise produce a smaller but still
        // self-consistent sum.
        if (reason != etask::core::completion_reason::finished) {
            return {std::uint64_t{0}, std::uint32_t{0}, std::uint32_t{0}, std::uint32_t{0}};
        }
        return {_sum, std::uint32_t{8}, _first, _last};
    }
} // namespace sys::bulk
