//! etask:doc file d97a182add32
/**
* @file count_to.cpp
*
* @brief execute for a fixed number of ticks, then finish
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "count_to.hpp"

namespace sys::polled {
    count_to::count_to(std::uint8_t ticks, [[maybe_unused]] context& ctx) //! etask:sig
        : _ctx{ctx}, _target{ticks}
    {
        _ctx.count_to_recorder.reset();
        _ctx.count_to_recorder.ran(support::lifecycle::hook::construct);
    }

    void count_to::on_execute()
    {
        _ctx.count_to_recorder.ran(support::lifecycle::hook::execute);
    }

    bool count_to::is_finished()
    {
        _ctx.count_to_recorder.ran(support::lifecycle::hook::finish);

        // The termination condition is the task's own, read off the work it has
        // actually done rather than a tick counter of its own - so a manager
        // that skipped an on_execute() shows up as a task that never finishes,
        // not one that finishes early on a count nobody checked.
        return _ctx.count_to_recorder.executions() >= _target;
    }

    etask::core::outcome count_to::on_complete(etask::core::completion_reason reason)
    {
        _ctx.count_to_recorder.ran(support::lifecycle::hook::complete);
        return {
            _ctx.count_to_recorder.hooks(),
            _ctx.count_to_recorder.executions(),
            static_cast<std::uint8_t>(reason),
        };
    }
} // namespace sys::polled
