//! etask:doc file 7ee4f5d4fd2d
/**
* @file never_ends.cpp
*
* @brief never finishes on its own; only a directive ends it
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "never_ends.hpp"

namespace sys::polled {
    never_ends::never_ends([[maybe_unused]] context& ctx) //! etask:sig
        : _ctx{ctx}
    {
        _ctx.never_ends_recorder.reset();
        _ctx.never_ends_recorder.ran(support::lifecycle::hook::construct);
    }

    void never_ends::on_execute()
    {
        _ctx.never_ends_recorder.ran(support::lifecycle::hook::execute);
    }

    bool never_ends::is_finished()
    {
        _ctx.never_ends_recorder.ran(support::lifecycle::hook::finish);

        // Never, by construction. Every conclusion this task reaches therefore
        // came from outside it, which is what makes the reason it reports back
        // attributable to the caller rather than to a natural completion it
        // might have arrived at anyway.
        return false;
    }

    etask::core::outcome never_ends::on_complete(etask::core::completion_reason reason)
    {
        _ctx.never_ends_recorder.ran(support::lifecycle::hook::complete);

        // The reason is echoed rather than interpreted: whether the caller's
        // exact byte survives the trip into this hook is the thing under test,
        // so mapping it to anything here would destroy the evidence.
        //
        // No `with_status()`. The two declared shapes differ only in status, and
        // the manager already picked the right one - `task_aborted` for the
        // generic reason, `task_completed_early` for a caller-supplied one.
        // Naming a status here would overwrite that decision with a guess,
        // when the decision is exactly what the host is asserting on.
        return {
            _ctx.never_ends_recorder.hooks(),
            _ctx.never_ends_recorder.executions(),
            static_cast<std::uint8_t>(reason),
        };
    }
} // namespace sys::polled
