//! etask:doc file 1cc431d987e4
/**
* @file never_ends.hpp
*
* @brief never finishes on its own; only a directive ends it
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_POLLED_NEVER_ENDS_HPP_
#define SYS_POLLED_NEVER_ENDS_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::polled {
    //! etask:doc class 85a17ad96270
    /**
    * @brief never finishes on its own; only a directive ends it
    *
    * `is_finished()` is permanently false, so every conclusion this task
    * reaches was forced from outside. That makes it the subject for the
    * force-complete cases: the reason it reports back could not have come
    * from a natural completion.
    *
    * A polled_task: on_execute() runs each tick until is_finished()
    * returns true (or the task is completed externally), then
    * on_complete(). It cannot be paused - that is a stateful_task.
    * See etask::core::polled_task.
    */
    //! etask:end doc class
    class never_ends : public polled_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        never_ends(context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Whether the task is done; polled after each on_execute().
        *
        * Return true once there is no work left; the manager then calls
        * on_complete() and removes the task.
        *
        * To finish unconditionally after a single on_execute(), do not write
        * `return true;` here - declare the task an oneshot_task in the schema.
        * That says so plainly and seals it, so a later edit cannot quietly turn
        * the task into something that never finishes.
        *
        * @return true when finished, false to keep running.
        */
        bool is_finished() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return One of this task's declared result shapes. The status code
        *         the reply carries is what tells the peer which shape it got,
        *         so pick the status *and* the values together:
        *
        *         aborted (0x21):
        *           - hooks : std::uint8_t
        *           - executions : std::uint8_t
        *           - reason : std::uint8_t
        *           `return etask::core::outcome{hooks, executions, reason}
        *               .with_status(etask::core::status_code::task_aborted);`
        *
        *         task_completed_early (0x28):
        *           - hooks : std::uint8_t
        *           - executions : std::uint8_t
        *           - reason : std::uint8_t
        *           `return etask::core::outcome{hooks, executions, reason}
        *               .with_status(etask::core::status_code::task_completed_early);`
        *
        *         Returning values with no status keeps the manager's own code
        *         (task_finished / task_aborted). A shape not listed here is not
        *         in the schema, so no peer knows how to decode it.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::polled_never_ends;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        *
        * Empty: this task takes no parameters.
        */
        using params = etools::meta::typelist<>;

        /**
        * @brief Names the `polled` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 3;   // generated::scopes::polled
        //! etask:wire end

    private:
        /// @brief The scope's ledger for this task. See `context::never_ends_recorder`.
        context& _ctx;
    };
} // namespace sys::polled
#endif // SYS_POLLED_NEVER_ENDS_HPP_
