//! etask:doc file c77fb1a4b145
/**
* @file telemetry.cpp
*
* @brief the project's widest result
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "telemetry.hpp"
#include "support/fixtures.hpp"

namespace sys::wide {
    telemetry::telemetry([[maybe_unused]] context& ctx) //! etask:sig
    {
    }
    void telemetry::on_execute()
    {
        // Constants; see support/fixtures.hpp.
    }
    etask::core::outcome telemetry::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // Fourteen distinct doubles, spelled out rather than looped, because
        // `return {...}` is a variadic pack and there is no runtime way to build
        // one from an array - which is itself the shape of the guarantee: the
        // types are fixed at the call site, so `eser` knows the exact width at
        // compile time and the 112 bytes this occupies are the 112 the generator
        // sized the frame for.
        //
        // Each channel is `wide_base + i`, so every value differs from its
        // neighbours. A shape this wide is exactly where an off-by-one slot would
        // hide: fourteen copies of one number would decode identically whether or
        // not the reader were a slot out.
        namespace fx = support::fixtures;
        return {
            fx::wide_base +  0.0, fx::wide_base +  1.0, fx::wide_base +  2.0,
            fx::wide_base +  3.0, fx::wide_base +  4.0, fx::wide_base +  5.0,
            fx::wide_base +  6.0, fx::wide_base +  7.0, fx::wide_base +  8.0,
            fx::wide_base +  9.0, fx::wide_base + 10.0, fx::wide_base + 11.0,
            fx::wide_base + 12.0, fx::wide_base + 13.0,
        };
    }
} // namespace sys::wide
