//! etask:doc file 880fc9321775
/**
* @file telemetry.hpp
*
* @brief the project's widest result
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_WIDE_TELEMETRY_HPP_
#define SYS_WIDE_TELEMETRY_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::wide {
    //! etask:doc class 54bdbac65268
    /**
    * @brief the project's widest result
    *
    * Fourteen doubles: 112 bytes, which with the uid and status byte makes a
    * 114-byte reply payload requirement. This is deliberately the single
    * widest shape in the schema, so `reply_payload_need` has exactly one
    * source and a host-side assertion on it is testing this task and nothing
    * else.
    *
    * Fourteen rather than "as many as fit": there is no schema-level ceiling
    * to sit just under, because the frame is sized *from* the declaration
    * rather than the declaration being checked against a fixed frame. So the
    * number is chosen to be comfortably past any small default buffer while
    * staying a size a real telemetry burst might be.
    *
    * A oneshot_task: an instant_task with a return value. The constructor
    * is the whole job - it is finished the moment it exists - and
    * on_complete() produces the result. is_finished() is sealed true in
    * the base and is not yours to override, so on_execute() is never
    * called: it must be defined because polled_task declares it pure, but
    * leave it empty. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class telemetry : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        telemetry(context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - d0 : double
        *           - d1 : double
        *           - d2 : double
        *           - d3 : double
        *           - d4 : double
        *           - d5 : double
        *           - d6 : double
        *           - d7 : double
        *           - d8 : double
        *           - d9 : double
        *           - d10 : double
        *           - d11 : double
        *           - d12 : double
        *           - d13 : double
        *         e.g. `return {d0, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::wide_telemetry;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        *
        * Empty: this task takes no parameters.
        */
        using params = etools::meta::typelist<>;

        /**
        * @brief Names the `wide` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 3;   // generated::scopes::wide
        //! etask:wire end
    };
} // namespace sys::wide
#endif // SYS_WIDE_TELEMETRY_HPP_
