// SPDX-License-Identifier: MIT
/**
* @file read.cpp
*
* @brief sample accel + gyro
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "read.hpp"

namespace system::sensors::imu {
    read::read([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void read::on_start()
    {
    }
    void read::on_execute()
    {
    }
    void read::on_pause()
    {
    }
    void read::on_resume()
    {
    }
    bool read::is_finished()
    {
        return true;
    }
    etools::memory::buffer<> read::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: pack and return the task result (branch on `reason`).
        return {};
    }
} // namespace system::sensors::imu
