//! etask:doc file 74c8dbfbc7d5
/**
* @file sample.cpp
*
* @brief read one counter
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "sample.hpp"

namespace sys::telemetry {
    sample::sample(std::uint8_t channel, [[maybe_unused]] context& ctx) //! etask:sig
        : _channel{channel}
    {
    }

    void sample::on_execute()
    {
    }

    etask::core::outcome sample::on_complete(etask::core::completion_reason reason)
    {
        // Derived from the channel rather than read from hardware: this project
        // has no sensor, and the point of the value is that the host can predict
        // it exactly. The offset and multiplier make the result depend on the
        // argument in a way a zero-filled or wrongly-routed request cannot
        // accidentally reproduce - `channel` alone would collide with a frame
        // that simply echoed a byte back.
        if (reason != etask::core::completion_reason::finished) return {std::uint16_t{0}};
        return {static_cast<std::uint16_t>(0x1000u + _channel * 7u)};
    }
} // namespace sys::telemetry
