// SPDX-License-Identifier: MIT
/**
* @file move_to.cpp
*
* @brief move the hand to a target pose
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "move_to.hpp"

namespace system::arms::right {
    move_to::move_to(float x, float y, float z, std::uint8_t speed, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void move_to::on_start()
    {
    }
    void move_to::on_execute()
    {
    }
    void move_to::on_pause()
    {
    }
    void move_to::on_resume()
    {
    }
    bool move_to::is_finished()
    {
        return true;
    }
    etools::memory::buffer<> move_to::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: pack and return the task result (branch on `reason`).
        return {};
    }
} // namespace system::arms::right
