// SPDX-License-Identifier: MIT
/**
* @file calibrate.hpp
*
* @brief calibrate the gripper to a known zero
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#ifndef TASKS_GRIPPER_CALIBRATE_HPP_
#define TASKS_GRIPPER_CALIBRATE_HPP_
#include "../task.hpp"
#include "context.hpp"
#include <etools/memory/buffer.hpp>

namespace tasks::gripper {
    class calibrate : public task {
    public:
        calibrate(float tolerance, std::uint8_t retries, context& ctx); //! etask:sig
        void on_start() override;
        void on_execute() override;
        void on_pause() override;
        void on_resume() override;
        bool is_finished() override;
        etools::memory::buffer<> on_complete(bool interrupted) override;

        static constexpr global::task_id uid = global::task_id::gripper_calibrate;
    };
} // namespace tasks::gripper
#endif // TASKS_GRIPPER_CALIBRATE_HPP_
