// SPDX-License-Identifier: MIT
/**
* @file calibrate.cpp
*
* @brief calibrate the gripper to a known zero
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "calibrate.hpp"

namespace tasks::gripper {
    calibrate::calibrate(float tolerance, std::uint8_t retries, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void calibrate::on_start()
    {
    }
    void calibrate::on_execute()
    {
    }
    void calibrate::on_pause()
    {
    }
    void calibrate::on_resume()
    {
    }
    bool calibrate::is_finished()
    {
        return true;
    }
    etools::memory::buffer<> calibrate::on_complete([[maybe_unused]] bool interrupted)
    {
        // TODO: pack and return the task result.
        return {};
    }
} // namespace tasks::gripper
