// SPDX-License-Identifier: MIT
/**
* @file grasp.cpp
*
* @brief close the fingers until a force threshold is reached
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "grasp.hpp"

namespace tasks::gripper {
    grasp::grasp(std::uint16_t force, std::uint32_t timeout_ms, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void grasp::on_start()
    {
    }
    void grasp::on_execute()
    {
    }
    void grasp::on_pause()
    {
    }
    void grasp::on_resume()
    {
    }
    bool grasp::is_finished()
    {
        return true;
    }
    etools::memory::buffer<> grasp::on_complete([[maybe_unused]] bool interrupted)
    {
        // TODO: pack and return the task result.
        return {};
    }
} // namespace tasks::gripper
