// SPDX-License-Identifier: MIT
/**
* @file grasp.hpp
*
* @brief close the fingers until a force threshold is reached
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#ifndef TASKS_GRIPPER_GRASP_HPP_
#define TASKS_GRIPPER_GRASP_HPP_
#include "../task.hpp"
#include "context.hpp"
#include <etools/memory/buffer.hpp>

namespace tasks::gripper {
    class grasp : public task {
    public:
        grasp(std::uint16_t force, std::uint32_t timeout_ms, context& ctx); //! etask:sig
        void on_start() override;
        void on_execute() override;
        void on_pause() override;
        void on_resume() override;
        bool is_finished() override;
        etools::memory::buffer<> on_complete(bool interrupted) override;

        static constexpr global::task_id uid = global::task_id::gripper_grasp;
    };
} // namespace tasks::gripper
#endif // TASKS_GRIPPER_GRASP_HPP_
