// SPDX-License-Identifier: MIT
/**
* @file fly_to.cpp
*
* @brief fly to a waypoint
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "fly_to.hpp"

namespace sys::nav {
    fly_to::fly_to(double lat, double lon, float alt, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void fly_to::on_start()
    {
    }
    void fly_to::on_execute()
    {
    }
    void fly_to::on_pause()
    {
    }
    void fly_to::on_resume()
    {
    }
    bool fly_to::is_finished()
    {
        return true;
    }
} // namespace sys::nav
