//! etask:doc file c0dbd6cd3f9f
/**
* @file fly_to.cpp
*
* @brief fly to a waypoint
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "fly_to.hpp"

namespace sys::nav {
    fly_to::fly_to(double lat, double lon, float alt, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void fly_to::on_execute()
    {
    }
    void fly_to::on_pause()
    {
    }
    void fly_to::on_resume()
    {
    }
    bool fly_to::is_finished()
    {
        // TODO: return true once this task's work is done.
        return true;
    }
    etask::core::outcome fly_to::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: return one of this task's declared result shapes:
        //   finished: return {flight_time_s};
        //   aborted: return etask::core::outcome{lat, lon, alt}.with_status(etask::core::status_code::task_aborted);
        //   task_dependency_missing: return etask::core::outcome{}.with_status(etask::core::status_code::task_dependency_missing);
        return {};
    }
} // namespace sys::nav
