//! etask:doc file 5e903406078b
/**
* @file fly_to.hpp
*
* @brief fly to a waypoint
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_NAV_FLY_TO_HPP_
#define SYS_NAV_FLY_TO_HPP_
#include "../task.hpp"
#include "context.hpp"
#include <etask/core/outcome.hpp>

namespace sys::nav {
    //! etask:doc class e6a92e32c121
    /**
    * @brief fly to a waypoint
    *
    * Drives the craft toward a target latitude/longitude/altitude, holding
    * until it arrives. Long-running: keeps working across many ticks.
    *
    * Lifecycle: on_start() runs once, then on_execute() each tick until
    * is_finished() returns true (or an external completion), then
    * on_complete(). on_pause()/on_resume() bracket a pause. See
    * etask::core::task for the full contract.
    */
    //! etask:end doc class
    class fly_to : public task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param lat TODO: describe `lat`.
        * @param lon TODO: describe `lon`.
        * @param alt TODO: describe `alt`.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        fly_to(double lat, double lon, float alt, context& ctx); //! etask:sig

        /**
        * @brief One-time setup, run once before the first on_execute().
        *
        * Acquire hardware, latch constructor parameters into working state, arm
        * timers. Runs exactly once per instance, before any execute/pause/resume.
        * Leave empty if the task needs no setup.
        */
        void on_start() override;

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        */
        void on_execute() override;

        /**
        * @brief Run once when the task is paused.
        *
        * Most tasks need nothing here. Override when something must not persist
        * across a pause - stop a motor, release a bus, freeze an integrator - so
        * the paused state is safe. Pair with on_resume(). Leave empty otherwise.
        */
        void on_pause() override;

        /**
        * @brief Run once when a paused task resumes.
        *
        * The mirror of on_pause(): re-acquire or restart whatever it released.
        * Leave empty if on_pause() was empty.
        */
        void on_resume() override;

        /**
        * @brief Whether the task is done; polled after each on_execute().
        *
        * Return true once there is no work left; the manager then calls
        * on_complete() and removes the task. Returning true unconditionally makes
        * this a single-shot task that concludes after one on_execute().
        *
        * @return true when finished, false to keep running.
        */
        bool is_finished() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return One of this task's declared result shapes. The status code
        *         the reply carries is what tells the peer which shape it got,
        *         so pick the status *and* the values together:
        *
        *         finished (0x20):
        *           - flight_time_s : std::uint32_t
        *           `return {flight_time_s};`  (the default status;
        *           no with_status() needed)
        *
        *         aborted (0x21):
        *           - lat : double
        *           - lon : double
        *           - alt : float
        *           `return etask::core::outcome{lat, lon, alt}
        *               .with_status(etask::core::status_code::task_aborted);`
        *
        *         task_dependency_missing (0x25):
        *           `return etask::core::outcome{}
        *               .with_status(etask::core::status_code::task_dependency_missing);`
        *
        *         Returning values with no status keeps the manager's own code
        *         (task_finished / task_aborted). A shape not listed here is not
        *         in the schema, so no peer knows how to decode it.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        static constexpr global::task_id uid = global::task_id::nav_fly_to;
    };
} // namespace sys::nav
#endif // SYS_NAV_FLY_TO_HPP_
