//! etask:doc file 5e903406078b
/**
* @file fly_to.hpp
*
* @brief fly to a waypoint
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_NAV_FLY_TO_HPP_
#define SYS_NAV_FLY_TO_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::nav {
    //! etask:doc class 58bf77127289
    /**
    * @brief fly to a waypoint
    *
    * Drives the craft toward a target latitude/longitude/altitude, holding
    * until it arrives. Long-running: keeps working across many ticks.
    *
    * A stateful_task: on_execute() runs each tick until is_finished()
    * returns true (or the task is completed externally), then
    * on_complete(). on_pause()/on_resume() bracket a suspension.
    * See etask::core::stateful_task.
    */
    //! etask:end doc class
    class fly_to : public stateful_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param lat TODO: describe `lat`.
        * @param lon TODO: describe `lon`.
        * @param alt TODO: describe `alt`.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        fly_to(double lat, double lon, float alt, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Run once when the task is paused.
        *
        * Make the suspended state safe: stop a motor, release a bus, freeze an
        * integrator, save whatever partial progress must not be lost. Pair with
        * on_resume().
        *
        * This task is a stateful_task, which is a claim that it holds something
        * needing exactly this. If there is nothing to write here, it wants to be
        * a polled_task instead - and would stop paying for two vtable slots.
        */
        void on_pause() override;

        /**
        * @brief Run once when a paused task resumes.
        *
        * The mirror of on_pause(): re-acquire or restart whatever it released,
        * reinitialize timers, reload cached state. A task that releases something
        * on pause and never takes it back is a bug.
        */
        void on_resume() override;

        /**
        * @brief Whether the task is done; polled after each on_execute().
        *
        * Return true once there is no work left; the manager then calls
        * on_complete() and removes the task.
        *
        * To finish unconditionally after a single on_execute(), do not write
        * `return true;` here - declare the task an oneshot_task in the schema.
        * That says so plainly and seals it, so a later edit cannot quietly turn
        * the task into something that never finishes.
        *
        * @return true when finished, false to keep running.
        */
        bool is_finished() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return One of this task's declared result shapes. The status code
        *         the reply carries is what tells the peer which shape it got,
        *         so pick the status *and* the values together:
        *
        *         finished (0x20):
        *           - flight_time_s : std::uint32_t
        *           `return {flight_time_s};`  (the default status;
        *           no with_status() needed)
        *
        *         aborted (0x21):
        *           - lat : double
        *           - lon : double
        *           - alt : float
        *           `return etask::core::outcome{lat, lon, alt}
        *               .with_status(etask::core::status_code::task_aborted);`
        *
        *         task_dependency_missing (0x25):
        *           `return etask::core::outcome{}
        *               .with_status(etask::core::status_code::task_dependency_missing);`
        *
        *         Returning values with no status keeps the manager's own code
        *         (task_finished / task_aborted). A shape not listed here is not
        *         in the schema, so no peer knows how to decode it.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::nav_fly_to;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<double, double, float>;

        /**
        * @brief Accessor for the `nav` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. See `generated/scopes.hpp`.
        */
        static constexpr auto scope = &generated::scopes::nav;
    };
} // namespace sys::nav
#endif // SYS_NAV_FLY_TO_HPP_
