//! etask:doc file aa3f69536b2b
/**
* @file hold.cpp
*
* @brief hold the current position
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "hold.hpp"

namespace sys::nav {
    hold::hold([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void hold::on_execute()
    {
    }
    bool hold::is_finished()
    {
        // TODO: return true once this task's work is done.
        return true;
    }
} // namespace sys::nav
