//! etask:doc file 78cf88813afc
/**
* @file hold.hpp
*
* @brief hold the current position
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_NAV_HOLD_HPP_
#define SYS_NAV_HOLD_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etools/meta/typelist.hpp>

namespace sys::nav {
    //! etask:doc class c13766dcd35f
    /**
    * @brief hold the current position
    *
    * A polled_task: on_execute() runs each tick until is_finished()
    * returns true (or the task is completed externally), then
    * on_complete(). It cannot be paused - that is a stateful_task.
    * See etask::core::polled_task.
    */
    //! etask:end doc class
    class hold : public polled_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        hold(context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Whether the task is done; polled after each on_execute().
        *
        * Return true once there is no work left; the manager then calls
        * on_complete() and removes the task.
        *
        * To finish unconditionally after a single on_execute(), do not write
        * `return true;` here - declare the task an oneshot_task in the schema.
        * That says so plainly and seals it, so a later edit cannot quietly turn
        * the task into something that never finishes.
        *
        * @return true when finished, false to keep running.
        */
        bool is_finished() override;

        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::nav_hold;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        *
        * Empty: this task takes no parameters.
        */
        using params = etools::meta::typelist<>;

        /**
        * @brief Accessor for the `nav` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. See `generated/scopes.hpp`.
        */
        static constexpr auto scope = &generated::scopes::nav;
    };
} // namespace sys::nav
#endif // SYS_NAV_HOLD_HPP_
