//! etask:doc file 25fc209c9840
/**
* @file land.cpp
*
* @brief descend and touch down
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "land.hpp"

namespace sys::nav {
    land::land([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void land::on_start()
    {
    }
    void land::on_execute()
    {
    }
    void land::on_pause()
    {
    }
    void land::on_resume()
    {
    }
    bool land::is_finished()
    {
        return true;
    }
} // namespace sys::nav
