//! etask:doc file e757866c0ea9
/**
* @file fix.cpp
*
* @brief acquire a position fix
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "fix.hpp"

namespace sys::sensors::gps {
    fix::fix([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void fix::on_start()
    {
    }
    void fix::on_execute()
    {
    }
    void fix::on_pause()
    {
    }
    void fix::on_resume()
    {
    }
    bool fix::is_finished()
    {
        return true;
    }
    etask::core::outcome fix::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: return the task result values (branch on `reason`).
        return {};
    }
} // namespace sys::sensors::gps
