// SPDX-License-Identifier: MIT
/**
* @file hold.cpp
*
* @brief hold the current position
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "hold.hpp"

namespace system::nav {
    hold::hold([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void hold::on_start()
    {
    }
    void hold::on_execute()
    {
    }
    void hold::on_pause()
    {
    }
    void hold::on_resume()
    {
    }
    bool hold::is_finished()
    {
        return true;
    }
} // namespace system::nav
