// SPDX-License-Identifier: MIT
/**
* @file land.cpp
*
* @brief descend and touch down
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "land.hpp"

namespace system::nav {
    land::land([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void land::on_start()
    {
    }
    void land::on_execute()
    {
    }
    void land::on_pause()
    {
    }
    void land::on_resume()
    {
    }
    bool land::is_finished()
    {
        return true;
    }
} // namespace system::nav
