//! etask:doc file cace27eb213d
/**
* @file grasp.hpp
*
* @brief close the gripper until a force threshold
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_ARMS_RIGHT_GRASP_HPP_
#define SYS_ARMS_RIGHT_GRASP_HPP_
#include "../../task.hpp"
#include "context.hpp"
#include <etask/core/outcome.hpp>

namespace sys::arms::right {
    //! etask:doc class 07d8bdf0cf6f
    /**
    * @brief close the gripper until a force threshold
    *
    * A polled_task: on_execute() runs each tick until is_finished()
    * returns true (or the task is completed externally), then
    * on_complete(). It cannot be paused - that is a stateful_task.
    * See etask::core::polled_task.
    */
    //! etask:end doc class
    class grasp : public polled_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param force TODO: describe `force`.
        * @param timeout_ms TODO: describe `timeout_ms`.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        grasp(std::uint16_t force, std::uint32_t timeout_ms, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Whether the task is done; polled after each on_execute().
        *
        * Return true once there is no work left; the manager then calls
        * on_complete() and removes the task.
        *
        * To finish unconditionally after a single on_execute(), do not write
        * `return true;` here - declare the task an oneshot_task in the schema.
        * That says so plainly and seals it, so a later edit cannot quietly turn
        * the task into something that never finishes.
        *
        * @return true when finished, false to keep running.
        */
        bool is_finished() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - [0] : std::uint8_t
        *           - [1] : float
        *         e.g. `return {v0, v1};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        static constexpr global::task_id uid = global::task_id::arms_right_grasp;
    };
} // namespace sys::arms::right
#endif // SYS_ARMS_RIGHT_GRASP_HPP_
