//! etask:doc file 8a350492ca4b
/**
* @file grasp.cpp
*
* @brief close the gripper until a force threshold
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "grasp.hpp"

namespace sys::arms::right {
    grasp::grasp(std::uint16_t force, std::uint32_t timeout_ms, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void grasp::on_start()
    {
    }
    void grasp::on_execute()
    {
    }
    void grasp::on_pause()
    {
    }
    void grasp::on_resume()
    {
    }
    bool grasp::is_finished()
    {
        return true;
    }
    etask::core::outcome grasp::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: return the task result values (branch on `reason`).
        return {};
    }
} // namespace sys::arms::right
