//! etask:doc file 95841e62365a
/**
* @file move_to.cpp
*
* @brief move the hand to a target pose
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "move_to.hpp"

namespace sys::arms::right {
    move_to::move_to(float x, float y, float z, std::uint8_t speed, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void move_to::on_execute()
    {
    }
    void move_to::on_pause()
    {
    }
    void move_to::on_resume()
    {
    }
    bool move_to::is_finished()
    {
        // TODO: return true once this task's work is done.
        return true;
    }
    etask::core::outcome move_to::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: return the task result values (branch on `reason`).
        return {};
    }
} // namespace sys::arms::right
