//! etask:doc file 1a9f5f9a3597
/**
* @file stop.cpp
*
* @brief halt the arm immediately
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "stop.hpp"

namespace sys::arms::right {
    stop::stop([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: do the command's work here - this constructor *is* the task.
        // It runs on arrival and the object is destroyed as this returns.
    }
} // namespace sys::arms::right
