//! etask:doc file 14e555a84a3b
/**
* @file read.hpp
*
* @brief sample accel + gyro
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_SENSORS_IMU_READ_HPP_
#define SYS_SENSORS_IMU_READ_HPP_
#include "../../task.hpp"
#include "context.hpp"
#include <etask/core/outcome.hpp>

namespace sys::sensors::imu {
    //! etask:doc class 3703196ff12f
    /**
    * @brief sample accel + gyro
    *
    * One-shot read of the six IMU axes (three accelerometer, three
    * gyroscope). Samples in on_execute(); a oneshot_task concludes
    * after that single step.
    *
    * A oneshot_task: on_execute() runs once, then on_complete() produces
    * the result. is_finished() is sealed true in the base and is not
    * yours to override. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class read : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        read(context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - ax : float
        *           - ay : float
        *           - az : float
        *           - gx : float
        *           - gy : float
        *           - gz : float
        *         e.g. `return {ax, ay, az, gx, gy, gz};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        static constexpr global::task_id uid = global::task_id::sensors_imu_read;
    };
} // namespace sys::sensors::imu
#endif // SYS_SENSORS_IMU_READ_HPP_
