// SPDX-License-Identifier: MIT
/**
* @file read.hpp
*
* @brief sample accel + gyro
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#ifndef SYS_SENSORS_IMU_READ_HPP_
#define SYS_SENSORS_IMU_READ_HPP_
#include "../../task.hpp"
#include "context.hpp"
#include <etools/memory/buffer.hpp>

namespace sys::sensors::imu {
    /**
    * @brief sample accel + gyro
    *
    * One-shot read of the six IMU axes (three accelerometer, three
    * gyroscope). Samples in on_execute() and reports finished.
    *
    * Lifecycle: on_start() runs once, then on_execute() each tick until
    * is_finished() returns true (or an external completion), then
    * on_complete(). on_pause()/on_resume() bracket a pause. See
    * etask::core::task for the full contract.
    */
    class read : public task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        read(context& ctx); //! etask:sig

        /**
        * @brief One-time setup, run once before the first on_execute().
        *
        * Acquire hardware, latch constructor parameters into working state, arm
        * timers. Runs exactly once per instance, before any execute/pause/resume.
        * Leave empty if the task needs no setup.
        */
        void on_start() override;

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        */
        void on_execute() override;

        /**
        * @brief Run once when the task is paused.
        *
        * Most tasks need nothing here. Override when something must not persist
        * across a pause - stop a motor, release a bus, freeze an integrator - so
        * the paused state is safe. Pair with on_resume(). Leave empty otherwise.
        */
        void on_pause() override;

        /**
        * @brief Run once when a paused task resumes.
        *
        * The mirror of on_pause(): re-acquire or restart whatever it released.
        * Leave empty if on_pause() was empty.
        */
        void on_resume() override;

        /**
        * @brief Whether the task is done; polled after each on_execute().
        *
        * Return true once there is no work left; the manager then calls
        * on_complete() and removes the task. Returning true unconditionally makes
        * this a single-shot task that concludes after one on_execute().
        *
        * @return true when finished, false to keep running.
        */
        bool is_finished() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return A buffer packing this task's declared return values, in order:
        *           - ax : float
        *           - ay : float
        *           - az : float
        *           - gx : float
        *           - gy : float
        *           - gz : float
        *         On a forced completion you may return an empty buffer if no
        *         meaningful result applies.
        */
        etools::memory::buffer<> on_complete(etask::core::completion_reason reason) override;

        static constexpr global::task_id uid = global::task_id::sensors_imu_read;
    };
} // namespace sys::sensors::imu
#endif // SYS_SENSORS_IMU_READ_HPP_
