//! etask:doc file 9249a9103f41
/**
* @file ping.cpp
*
* @brief a root-level task, belonging to no subsystem
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "ping.hpp"

namespace sys {
    ping::ping([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void ping::on_execute()
    {
    }

    etask::core::outcome ping::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // Unconditionally true, and unconditional on purpose: this task's only
        // claim is that the device answered at all, which is as true of an
        // aborted ping as of a finished one. It is reachable over neither link
        // in this project - a root-level task belongs to no subsystem, so no
        // `subsystems:` list can name it - and exists to make that fact
        // observable rather than to be called.
        return {true};
    }
} // namespace sys
