//! etask:doc file 57ee01d23447
/**
* @file sample.cpp
*
* @brief report this probe's identity
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "sample.hpp"
#include "support/witness.hpp"

namespace sys::mesh::s1::n2::p0 {
    sample::sample([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void sample::on_execute()
    {
    }
    etask::core::outcome sample::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // Identity, not a measurement: `uid` is this class's own
        // `global::task_id`, fixed at compile time from its schema path. A task
        // running under another's registration would report that other number.
        const auto self = static_cast<std::uint16_t>(uid);
        support::witness::record(self, support::phase::completed);
        return {self};
    }
} // namespace sys::mesh::s1::n2::p0
