// SPDX-License-Identifier: MIT
/**
* @file read.hpp
*
* @brief sample the accelerometer
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#ifndef TASKS_SENSORS_IMU_READ_HPP_
#define TASKS_SENSORS_IMU_READ_HPP_
#include "../../task.hpp"
#include "context.hpp"
#include <etools/memory/buffer.hpp>

namespace tasks::sensors::imu {
    class read : public task {
    public:
        read(context& ctx); //! etask:sig
        void on_start() override;
        void on_execute() override;
        void on_pause() override;
        void on_resume() override;
        bool is_finished() override;
        etools::memory::buffer<> on_complete(bool interrupted) override;

        static constexpr global::task_id uid = global::task_id::sensors_imu_read;
    };
} // namespace tasks::sensors::imu
#endif // TASKS_SENSORS_IMU_READ_HPP_
