//! etask:doc file 116b168ff9d1
/**
* @file arm.cpp
*
* @brief arm this probe across ticks
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "arm.hpp"
#include "support/witness.hpp"

namespace sys::mesh::s2::n1::p2 {
    arm::arm(float threshold, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void arm::on_execute()
    {
    }
    bool arm::is_finished()
    {
        // Nothing here models real work - the tier is what is being
        // exercised, not the duration - so one tick is the whole task.
        return true;
    }
    etask::core::outcome arm::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // Identity, not a measurement: `uid` is this class's own
        // `global::task_id`, fixed at compile time from its schema path. A task
        // running under another's registration would report that other number.
        const auto self = static_cast<std::uint16_t>(uid);
        support::witness::record(self, support::phase::completed);
        return {self};
    }
} // namespace sys::mesh::s2::n1::p2
