//! etask:doc file 40c43c1d4b0c
/**
* @file everything.hpp
*
* @brief every scalar type once, in one call
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_WIDE_EVERYTHING_HPP_
#define SYS_WIDE_EVERYTHING_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::wide {
    //! etask:doc class e4e2ec13508f
    /**
    * @brief every scalar type once, in one call
    *
    * All twelve schema types in a single parameter list: 1+1+1+2+2+4+4+8+8
    * +4+8+4 = 47 bytes of arguments. The same twelve come back, so this is
    * also the widest *result* in the project, and it is what sizes the
    * reply direction: 47 plus the uid and status bytes is 49 payload bytes.
    *
    * Forty-nine is the number this whole project is pinned to, and it was
    * chosen rather than found. The ESP32's practical ceiling is far higher,
    * but the ESP8266 in `examples/esp8266_blink` shares the same generator,
    * and a frame that will not fit the smaller of the two targets makes the
    * schema unusable on it. Under 64 bytes of payload the frame stays
    * inside a single ecomm packet on every board the project supports, and
    * leaves the reply - the larger direction here - room to echo it all
    * back.
    *
    * The return shape carries all twelve back, so this task is a true echo
    * rather than a fold. That is the point of sizing it here: the widest
    * call the project makes is still one whose every byte is checkable
    * individually, so a failure says *which type* drifted.
    *
    * A oneshot_task: on_execute() runs once, then on_complete() produces
    * the result. is_finished() is sealed true in the base and is not
    * yours to override. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class everything : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param b The value to echo back unchanged.
        * @param i8 The value to echo back unchanged.
        * @param u8 The value to echo back unchanged.
        * @param i16 The value to echo back unchanged.
        * @param u16 The value to echo back unchanged.
        * @param i32 The value to echo back unchanged.
        * @param u32 The value to echo back unchanged.
        * @param i64 The value to echo back unchanged.
        * @param u64 The value to echo back unchanged.
        * @param f The value to echo back unchanged.
        * @param d The value to echo back unchanged.
        * @param n The value to echo back unchanged.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        everything(bool b, std::int8_t i8, std::uint8_t u8, std::int16_t i16, std::uint16_t u16, std::int32_t i32, std::uint32_t u32, std::int64_t i64, std::uint64_t u64, float f, double d, std::int32_t n, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - b : bool
        *           - i8 : std::int8_t
        *           - u8 : std::uint8_t
        *           - i16 : std::int16_t
        *           - u16 : std::uint16_t
        *           - i32 : std::int32_t
        *           - u32 : std::uint32_t
        *           - i64 : std::int64_t
        *           - u64 : std::uint64_t
        *           - f : float
        *           - d : double
        *           - n : std::int32_t
        *         e.g. `return {b, i8, u8, i16, u16, i32, u32, i64, u64, f, d, n};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::wide_everything;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<bool, std::int8_t, std::uint8_t, std::int16_t, std::uint16_t, std::int32_t, std::uint32_t, std::int64_t, std::uint64_t, float, double, std::int32_t>;

        /**
        * @brief Names the `wide` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 3;   // generated::scopes::wide
        //! etask:wire end

    private:
        // Held between the constructor and on_complete() at the exact width
        // the schema declared. Widening any of these - to `int` by promotion,
        // or to `double` by a toolchain that has no real float - would make
        // this task echo a value it never received, which is the drift the
        // whole project is looking for.
        bool _b;
        std::int8_t _i8;
        std::uint8_t _u8;
        std::int16_t _i16;
        std::uint16_t _u16;
        std::int32_t _i32;
        std::uint32_t _u32;
        std::int64_t _i64;
        std::uint64_t _u64;
        float _f;
        double _d;
        std::int32_t _n;
    };
} // namespace sys::wide
#endif // SYS_WIDE_EVERYTHING_HPP_
