//! etask:doc file ae6fe71577fe
/**
* @file everything.cpp
*
* @brief every scalar type once, in one call
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "everything.hpp"

namespace sys::wide {
    everything::everything(bool b, std::int8_t i8, std::uint8_t u8, std::int16_t i16, std::uint16_t u16, std::int32_t i32, std::uint32_t u32, std::int64_t i64, std::uint64_t u64, float f, double d, std::int32_t n, [[maybe_unused]] context& ctx) //! etask:sig
        : _b{b}
        , _i8{i8}
        , _u8{u8}
        , _i16{i16}
        , _u16{u16}
        , _i32{i32}
        , _u32{u32}
        , _i64{i64}
        , _u64{u64}
        , _f{f}
        , _d{d}
        , _n{n}
    {
        // Nothing else to do: the round trip is the whole task, and
        // holding the arguments is the whole of holding it.
    }
    void everything::on_execute()
    {
        // Deliberately empty. A oneshot_task still gets one execute tick, but
        // there is no work to do in it: the round trip is the measurement, and
        // both halves of it already happened - the arguments were unpacked into
        // the constructor, and the result is produced by on_complete(). Doing
        // anything here would only add a step the driver cannot observe.
    }
    etask::core::outcome everything::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // `reason` is not branched on. Every declared shape here is the
        // echo, so a forced completion should still report what arrived
        // rather than an empty result the driver could not tell from a
        // zeroed frame.
        return {_b, _i8, _u8, _i16, _u16, _i32, _u32, _i64, _u64, _f, _d, _n};
    }
} // namespace sys::wide
