//! etask:doc file c070d9c9a723
/**
* @file folded_mixed.cpp
*
* @brief a wide mixed list, folded over the raw argument bytes
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "folded_mixed.hpp"
#include "../../support/fold.hpp"

namespace sys::wide {
    folded_mixed::folded_mixed(std::uint8_t u8, double d, std::uint8_t u8b, std::int64_t i64, bool b, float f, std::int16_t i16, std::uint32_t u32, [[maybe_unused]] context& ctx) //! etask:sig
        : _digest{support::fold::offset_basis}
    {
        // Folded here rather than in on_execute(): the arguments are alive
        // exactly once, in this call, and a digest taken later would be a
        // digest of whatever survived being stored - which is the very
        // thing under test.
        _digest = support::fold::fold_one(_digest, u8);
        _digest = support::fold::fold_one(_digest, d);
        _digest = support::fold::fold_one(_digest, u8b);
        _digest = support::fold::fold_one(_digest, i64);
        _digest = support::fold::fold_one(_digest, b);
        _digest = support::fold::fold_one(_digest, f);
        _digest = support::fold::fold_one(_digest, i16);
        _digest = support::fold::fold_one(_digest, u32);
    }
    void folded_mixed::on_execute()
    {
        // Deliberately empty. A oneshot_task still gets one execute tick, but
        // there is no work to do in it: the round trip is the measurement, and
        // both halves of it already happened - the arguments were unpacked into
        // the constructor, and the result is produced by on_complete(). Doing
        // anything here would only add a step the driver cannot observe.
    }
    etask::core::outcome folded_mixed::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // See the constructor: the digest already covers every argument,
        // so there is nothing left for `reason` to change.
        return {_digest};
    }
} // namespace sys::wide
