//! etask:doc file c6ae866d181d
/**
* @file folded_mixed.hpp
*
* @brief a wide mixed list, folded over the raw argument bytes
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_WIDE_FOLDED_MIXED_HPP_
#define SYS_WIDE_FOLDED_MIXED_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>
#include <cstdint>

namespace sys::wide {
    //! etask:doc class 25e84dba88ea
    /**
    * @brief a wide mixed list, folded over the raw argument bytes
    *
    * `saturated`'s fold applied to a list of every width, so the digest
    * covers narrow types too. A device that widened a uint8 argument to a
    * word before folding it disagrees here while every echo task still
    * passes - which is the drift a per-type echo cannot see, because an
    * echo never shows how the value was *held* between unpacking and
    * repacking.
    *
    * The digest is over each argument's own wire width, not over a
    * promoted one: see verify.py's `fold`, which is the normative
    * description of what the device must compute.
    *
    * A oneshot_task: on_execute() runs once, then on_complete() produces
    * the result. is_finished() is sealed true in the base and is not
    * yours to override. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class folded_mixed : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param u8 A value folded into the digest, at its own wire width.
        * @param d A value folded into the digest, at its own wire width.
        * @param u8b A value folded into the digest, at its own wire width.
        * @param i64 A value folded into the digest, at its own wire width.
        * @param b A value folded into the digest, at its own wire width.
        * @param f A value folded into the digest, at its own wire width.
        * @param i16 A value folded into the digest, at its own wire width.
        * @param u32 A value folded into the digest, at its own wire width.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        folded_mixed(std::uint8_t u8, double d, std::uint8_t u8b, std::int64_t i64, bool b, float f, std::int16_t i16, std::uint32_t u32, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - digest : std::uint64_t
        *         e.g. `return {digest};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::wide_folded_mixed;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<std::uint8_t, double, std::uint8_t, std::int64_t, bool, float, std::int16_t, std::uint32_t>;

        /**
        * @brief Names the `wide` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 3;   // generated::scopes::wide
        //! etask:wire end

    private:
        // The digest, computed in the constructor rather than held as fields:
        // the arguments are only needed once, and folding them on arrival keeps
        // the task's storage independent of how long its parameter list grows.
        std::uint64_t _digest;
    };
} // namespace sys::wide
#endif // SYS_WIDE_FOLDED_MIXED_HPP_
