//! etask:doc file 4dcac1d3502d
/**
* @file saturated.hpp
*
* @brief six doubles - the widest single-type list, folded on return
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_WIDE_SATURATED_HPP_
#define SYS_WIDE_SATURATED_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>
#include <cstdint>

namespace sys::wide {
    //! etask:doc class 7dc8c860019b
    /**
    * @brief six doubles - the widest single-type list, folded on return
    *
    * Forty-eight bytes of arguments, one byte more than `everything`, and
    * so the task that drives the request frame: 48 plus the directive and
    * uid bytes is 50 payload bytes, the widest request here. Six doubles
    * rather than a mixture because a same-width list removes ordering as a
    * variable: if this fails and `everything` passes, the fault is length,
    * not layout.
    *
    * The return shape is a fold, not an echo, and deliberately so. Echoing
    * six doubles back would make the reply frame the widest in the project
    * and change what this task measures - the request direction - so the
    * task returns a single uint64 that every argument contributes to
    * instead. The driver computes the same fold and compares.
    *
    * The fold is a bitwise FNV-1a over each argument's eight IEEE-754
    * bytes, chosen because it is exactly reproducible in Python (see
    * verify.py) and because it is bit-sensitive: a device that truncated
    * any of the six to float would change the digest, where a sum or an
    * xor of the values themselves could cancel.
    *
    * A oneshot_task: on_execute() runs once, then on_complete() produces
    * the result. is_finished() is sealed true in the base and is not
    * yours to override. See etask::core::oneshot_task.
    */
    //! etask:end doc class
    class saturated : public oneshot_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param a A value folded into the digest, at its own wire width.
        * @param b A value folded into the digest, at its own wire width.
        * @param c A value folded into the digest, at its own wire width.
        * @param d A value folded into the digest, at its own wire width.
        * @param e A value folded into the digest, at its own wire width.
        * @param f A value folded into the digest, at its own wire width.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        saturated(double a, double b, double c, double d, double e, double f, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return This task's result - just return the values, in order:
        *           - digest : std::uint64_t
        *         e.g. `return {digest};` - the values are
        *         serialized straight into the outgoing packet. Return `{}` on a
        *         forced completion if no meaningful result applies.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::wide_saturated;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<double, double, double, double, double, double>;

        /**
        * @brief Names the `wide` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 3;   // generated::scopes::wide
        //! etask:wire end

    private:
        // The digest, computed in the constructor rather than held as fields:
        // the arguments are only needed once, and folding them on arrival keeps
        // the task's storage independent of how long its parameter list grows.
        std::uint64_t _digest;
    };
} // namespace sys::wide
#endif // SYS_WIDE_SATURATED_HPP_
