//! etask:doc file 5b0aa44a65e8
/**
* @file saturated.cpp
*
* @brief six doubles - the widest single-type list, folded on return
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "saturated.hpp"
#include "../../support/fold.hpp"

namespace sys::wide {
    saturated::saturated(double a, double b, double c, double d, double e, double f, [[maybe_unused]] context& ctx) //! etask:sig
        : _digest{support::fold::offset_basis}
    {
        // Folded here rather than in on_execute(): the arguments are alive
        // exactly once, in this call, and a digest taken later would be a
        // digest of whatever survived being stored - which is the very
        // thing under test.
        _digest = support::fold::fold_one(_digest, a);
        _digest = support::fold::fold_one(_digest, b);
        _digest = support::fold::fold_one(_digest, c);
        _digest = support::fold::fold_one(_digest, d);
        _digest = support::fold::fold_one(_digest, e);
        _digest = support::fold::fold_one(_digest, f);
    }
    void saturated::on_execute()
    {
        // Deliberately empty. A oneshot_task still gets one execute tick, but
        // there is no work to do in it: the round trip is the measurement, and
        // both halves of it already happened - the arguments were unpacked into
        // the constructor, and the result is produced by on_complete(). Doing
        // anything here would only add a step the driver cannot observe.
    }
    etask::core::outcome saturated::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // See the constructor: the digest already covers every argument,
        // so there is nothing left for `reason` to change.
        return {_digest};
    }
} // namespace sys::wide
