// SPDX-License-Identifier: MIT
/**
* @file move_to.hpp
*
* @brief move the joint to an absolute angle
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#ifndef TASKS_ARM_BASE_MOVE_TO_HPP_
#define TASKS_ARM_BASE_MOVE_TO_HPP_
#include "../../task.hpp"
#include "context.hpp"
#include <etools/memory/buffer.hpp>

namespace tasks::arm::base {
    class move_to : public task {
    public:
        move_to(float angle, std::uint8_t speed, context& ctx); //! etask:sig
        void on_start() override;
        void on_execute() override;
        void on_pause() override;
        void on_resume() override;
        bool is_finished() override;
        etools::memory::buffer<> on_complete(bool interrupted) override;

        static constexpr global::task_id uid = global::task_id::arm_base_move_to;
    };
} // namespace tasks::arm::base
#endif // TASKS_ARM_BASE_MOVE_TO_HPP_
