// SPDX-License-Identifier: MIT
/**
* @file move_to.cpp
*
* @brief move the joint to an absolute angle
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "move_to.hpp"

namespace tasks::arm::base {
    move_to::move_to(float angle, std::uint8_t speed, [[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void move_to::on_start()
    {
    }
    void move_to::on_execute()
    {
    }
    void move_to::on_pause()
    {
    }
    void move_to::on_resume()
    {
    }
    bool move_to::is_finished()
    {
        return true;
    }
    etools::memory::buffer<> move_to::on_complete([[maybe_unused]] bool interrupted)
    {
        // TODO: pack and return the task result.
        return {};
    }
} // namespace tasks::arm::base
