//! etask:doc file 05955920640a
/**
* @file stop.hpp
*
* @brief plant the foot and hold
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_LEGS_RIGHT_STOP_HPP_
#define SYS_LEGS_RIGHT_STOP_HPP_
#include "../../task.hpp"
#include "context.hpp"

namespace sys::legs::right {
    //! etask:doc class 43f265ee8d66
    /**
    * @brief plant the foot and hold
    *
    * Lifecycle: on_start() runs once, then on_execute() each tick until
    * is_finished() returns true (or an external completion), then
    * on_complete(). on_pause()/on_resume() bracket a pause. See
    * etask::core::task for the full contract.
    */
    //! etask:end doc class
    class stop : public task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        stop(context& ctx); //! etask:sig

        /**
        * @brief One-time setup, run once before the first on_execute().
        *
        * Acquire hardware, latch constructor parameters into working state, arm
        * timers. Runs exactly once per instance, before any execute/pause/resume.
        * Leave empty if the task needs no setup.
        */
        void on_start() override;

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        */
        void on_execute() override;

        /**
        * @brief Run once when the task is paused.
        *
        * Most tasks need nothing here. Override when something must not persist
        * across a pause - stop a motor, release a bus, freeze an integrator - so
        * the paused state is safe. Pair with on_resume(). Leave empty otherwise.
        */
        void on_pause() override;

        /**
        * @brief Run once when a paused task resumes.
        *
        * The mirror of on_pause(): re-acquire or restart whatever it released.
        * Leave empty if on_pause() was empty.
        */
        void on_resume() override;

        /**
        * @brief Whether the task is done; polled after each on_execute().
        *
        * Return true once there is no work left; the manager then calls
        * on_complete() and removes the task. Returning true unconditionally makes
        * this a single-shot task that concludes after one on_execute().
        *
        * @return true when finished, false to keep running.
        */
        bool is_finished() override;

        static constexpr global::task_id uid = global::task_id::legs_right_stop;
    };
} // namespace sys::legs::right
#endif // SYS_LEGS_RIGHT_STOP_HPP_
