//! etask:doc file 05955920640a
/**
* @file stop.hpp
*
* @brief plant the foot and hold
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_LEGS_RIGHT_STOP_HPP_
#define SYS_LEGS_RIGHT_STOP_HPP_
#include "../../task.hpp"
#include "context.hpp"

namespace sys::legs::right {
    //! etask:doc class 3415cd2c4b12
    /**
    * @brief plant the foot and hold
    *
    * An instant_task: a fire-and-forget command. It runs to completion
    * inside the call that delivers it - the constructor is the whole task -
    * and is then destroyed. It occupies no storage, never sees an update()
    * tick, and sends no reply, so it cannot be paused, resumed, or
    * completed. See etask::core::instant_task.
    */
    //! etask:end doc class
    class stop : public instant_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        stop(context& ctx); //! etask:sig

        static constexpr global::task_id uid = global::task_id::legs_right_stop;
    };
} // namespace sys::legs::right
#endif // SYS_LEGS_RIGHT_STOP_HPP_
