// SPDX-License-Identifier: MIT
/**
* @file reboot.cpp
*
* @brief reboot the controller
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "reboot.hpp"

namespace tasks {
    reboot::reboot() //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void reboot::on_start()
    {
    }
    void reboot::on_execute()
    {
    }
    void reboot::on_pause()
    {
    }
    void reboot::on_resume()
    {
    }
    bool reboot::is_finished()
    {
        return true;
    }
} // namespace tasks
