//! etask:doc file 001541b50c76
/**
* @file audit.cpp
*
* @brief derived, among pinned siblings
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "audit.hpp"
#include "support/witness.hpp"

namespace sys::bus::reserve {
    audit::audit([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void audit::on_execute()
    {
    }
    etask::core::outcome audit::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // Identity, not a measurement: `uid` is this class's own
        // `global::task_id`, fixed at compile time from its schema path. A task
        // running under another's registration would report that other number.
        const auto self = static_cast<std::uint16_t>(uid);
        support::witness::record(self, support::phase::completed);
        return {self};
    }
} // namespace sys::bus::reserve
