//! etask:doc file 075147d85c70
/**
* @file resumable.cpp
*
* @brief a long task that pauses and resumes safely
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "resumable.hpp"

namespace sys::stateful {
    resumable::resumable(std::uint8_t run_for, [[maybe_unused]] context& ctx) //! etask:sig
        : _ctx{ctx}, _run_for{run_for}
    {
        _ctx.recorder.reset();
        _ctx.recorder.ran(support::lifecycle::hook::construct);
    }

    void resumable::on_execute()
    {
        _ctx.recorder.ran(support::lifecycle::hook::execute);
    }

    void resumable::on_pause()
    {
        _ctx.recorder.ran(support::lifecycle::hook::pause);

        // Freeze the progress marker. A real task would be stopping a motor or
        // releasing a bus here; what has to be made safe in this one is the
        // evidence, so the count is latched at the instant of suspension and
        // compared against the count at resume.
        _executions_at_pause = _ctx.recorder.executions();
    }

    void resumable::on_resume()
    {
        // The mirror of on_pause(). Nothing is un-frozen here on purpose:
        // `_executions_at_pause` has to survive until on_complete() reports it,
        // since the comparison it feeds - executions at pause against executions
        // at the end - is the whole proof that the suspension was honored.
        _ctx.recorder.ran(support::lifecycle::hook::resume);
    }

    bool resumable::is_finished()
    {
        _ctx.recorder.ran(support::lifecycle::hook::finish);
        return _ctx.recorder.executions() >= _run_for;
    }

    etask::core::outcome resumable::on_complete(etask::core::completion_reason reason)
    {
        _ctx.recorder.ran(support::lifecycle::hook::complete);

        // Unlabelled, as in `never_ends`: the manager's own status already
        // distinguishes the natural ending from the forced one, and that
        // distinction is what the host checks.
        return {
            _ctx.recorder.hooks(),
            _ctx.recorder.executions(),
            _executions_at_pause,
            _ctx.recorder.pauses(),
            _ctx.recorder.resumes(),
            static_cast<std::uint8_t>(reason),
        };
    }
} // namespace sys::stateful
