//! etask:doc file 78ed5864a73a
/**
* @file resumable.hpp
*
* @brief a long task that pauses and resumes safely
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_STATEFUL_RESUMABLE_HPP_
#define SYS_STATEFUL_RESUMABLE_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etask/core/outcome.hpp>
#include <etools/meta/typelist.hpp>

namespace sys::stateful {
    //! etask:doc class 0100a09a6267
    /**
    * @brief a long task that pauses and resumes safely
    *
    * Runs for a set number of execution steps, which a suspension delays
    * rather than cancels. While suspended it must not execute, so it
    * returns both the total execution count and the count taken at the
    * moment of on_pause(): if those differ across a paused stretch, the
    * manager executed a task it had agreed to suspend.
    *
    * A stateful_task: on_execute() runs each tick until is_finished()
    * returns true (or the task is completed externally), then
    * on_complete(). on_pause()/on_resume() bracket a suspension.
    * See etask::core::stateful_task.
    */
    //! etask:end doc class
    class resumable : public stateful_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param run_for How many `on_execute()` calls to run before reporting
        *        finished. Counted in executions rather than ticks, so a
        *        suspension postpones the ending instead of racing it.
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        resumable(std::uint8_t run_for, context& ctx); //! etask:sig

        /**
        * @brief One slice of work, run every update() tick while the task runs.
        *
        * Called repeatedly by the manager and must not block: do a little and
        * return so other tasks get their turn. Keeps running until is_finished()
        * returns true or the task is completed externally.
        *
        * Setup belongs in the constructor, not here - a task is built with its
        * parameters and scope context already in hand, after every board-level
        * initialization has run.
        */
        void on_execute() override;

        /**
        * @brief Run once when the task is paused.
        *
        * Make the suspended state safe: stop a motor, release a bus, freeze an
        * integrator, save whatever partial progress must not be lost. Pair with
        * on_resume().
        *
        * This task is a stateful_task, which is a claim that it holds something
        * needing exactly this. If there is nothing to write here, it wants to be
        * a polled_task instead - and would stop paying for two vtable slots.
        */
        void on_pause() override;

        /**
        * @brief Run once when a paused task resumes.
        *
        * The mirror of on_pause(): re-acquire or restart whatever it released,
        * reinitialize timers, reload cached state. A task that releases something
        * on pause and never takes it back is a bug.
        */
        void on_resume() override;

        /**
        * @brief Whether the task is done; polled after each on_execute().
        *
        * Return true once there is no work left; the manager then calls
        * on_complete() and removes the task.
        *
        * To finish unconditionally after a single on_execute(), do not write
        * `return true;` here - declare the task an oneshot_task in the schema.
        * That says so plainly and seals it, so a later edit cannot quietly turn
        * the task into something that never finishes.
        *
        * @return true when finished, false to keep running.
        */
        bool is_finished() override;

        /**
        * @brief Conclude the task and produce its result. Runs exactly once.
        *
        * Invoked by the manager as the task ends, on every path:
        *  - natural completion (reason == completion_reason::finished), after
        *    is_finished() returned true;
        *  - a forced completion requested through a channel (reason ==
        *    completion_reason::aborted, or a caller-supplied reason).
        * Branch on `reason` to decide what to return.
        *
        * @param reason Why the task is concluding. A system-only, input-only
        *               signal - see etask::core::completion_reason.
        * @return One of this task's declared result shapes. The status code
        *         the reply carries is what tells the peer which shape it got,
        *         so pick the status *and* the values together:
        *
        *         finished (0x20):
        *           - hooks : std::uint8_t
        *           - executions : std::uint8_t
        *           - executions_at_pause : std::uint8_t
        *           - pauses : std::uint8_t
        *           - resumes : std::uint8_t
        *           - reason : std::uint8_t
        *           `return {hooks, executions, executions_at_pause, pauses, resumes, reason};`  (the default status;
        *           no with_status() needed)
        *
        *         task_completed_early (0x28):
        *           - hooks : std::uint8_t
        *           - executions : std::uint8_t
        *           - executions_at_pause : std::uint8_t
        *           - pauses : std::uint8_t
        *           - resumes : std::uint8_t
        *           - reason : std::uint8_t
        *           `return etask::core::outcome{hooks, executions, executions_at_pause, pauses, resumes, reason}
        *               .with_status(etask::core::status_code::task_completed_early);`
        *
        *         Returning values with no status keeps the manager's own code
        *         (task_finished / task_aborted). A shape not listed here is not
        *         in the schema, so no peer knows how to decode it.
        */
        etask::core::outcome on_complete(etask::core::completion_reason reason) override;

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::stateful_resumable;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        */
        using params = etools::meta::typelist<std::uint8_t>;

        /**
        * @brief Names the `stateful` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 4;   // generated::scopes::stateful
        //! etask:wire end

    private:
        /// @brief The scope's ledger. See `context::recorder`.
        context& _ctx;

        /**
        * @brief The execution count as it stood when `on_pause()` last ran.
        *
        * Latched in the hook rather than compared afterwards, because "did the
        * task execute while suspended" is a question about a window that has
        * already closed by the time anyone can ask. With the count frozen at the
        * moment of suspension, the host compares it against the count at
        * `on_resume()` and gets the answer directly.
        *
        * 255 until a pause happens, which is not a count this task can otherwise
        * reach - so "never paused" cannot be mistaken for "paused at zero".
        */
        std::uint8_t _executions_at_pause{255};

        /**
        * @brief How many executions this task was asked for. Never mutated.
        *
        * The natural-completion path needs *some* end condition, or the
        * `finished` result shape could never be produced and half this task's
        * schema would be unreachable. Counting executions rather than ticks is
        * what makes a suspension postpone that ending rather than race it: a
        * paused task does not execute, so it does not approach its end either.
        */
        std::uint8_t _run_for;
    };
} // namespace sys::stateful
#endif // SYS_STATEFUL_RESUMABLE_HPP_
