//! etask:doc file 66c2cc7acc2b
/**
* @file ping.hpp
*
* @brief run on arrival and record it
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_INSTANT_PING_HPP_
#define SYS_INSTANT_PING_HPP_
#include "../task.hpp"
#include "context.hpp"
#include "../../generated/scopes.hpp"
#include <etools/meta/typelist.hpp>

namespace sys::instant {
    //! etask:doc class 8efae838cad8
    /**
    * @brief run on arrival and record it
    *
    * The whole task is its constructor. It bumps the scope recorder's
    * arrival counter, which is what the host reads back to prove the
    * command ran without any reply ever being sent.
    *
    * An instant_task: a fire-and-forget command. It runs to completion
    * inside the call that delivers it - the constructor is the whole task -
    * and is then destroyed. It occupies no storage, never sees an update()
    * tick, and sends no reply, so it cannot be paused, resumed, or
    * completed. See etask::core::instant_task.
    */
    //! etask:end doc class
    class ping : public instant_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        ping(context& ctx); //! etask:sig

        //! etask:wire begin - generated, rewritten on every generate
        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::instant_ping;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        *
        * Empty: this task takes no parameters.
        */
        using params = etools::meta::typelist<>;

        /**
        * @brief Names the `instant` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. The index selects an `etask::core::scope_binding`
        * specialization; `generated/scopes.hpp` emits one per scope.
        *
        * An index rather than the accessor itself because this value
        * ends up inside the unpacking adapter's mangled type name, and
        * a function pointer mangles as the whole function - tens of
        * bytes of typeinfo per task, which on a microcontroller is
        * flash. It resolves to the same accessor at compile time.
        */
        static constexpr etask::core::scope_index_t scope = 1;   // generated::scopes::instant
        //! etask:wire end
    };
} // namespace sys::instant
#endif // SYS_INSTANT_PING_HPP_
