//! etask:doc file a4c82d31376f
/**
* @file ping.cpp
*
* @brief run on arrival and record it
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "ping.hpp"

namespace sys::instant {
    ping::ping([[maybe_unused]] context& ctx) //! etask:sig
    {
        // The whole task. There is no hook to run later and no reply to send,
        // so the mark left here is the only thing that will outlive the call -
        // which is precisely what makes it the proof the command ran.
        ctx.recorder.ran(support::lifecycle::hook::construct);
    }
} // namespace sys::instant
