// SPDX-License-Identifier: MIT
/**
* @file fix.cpp
*
* @brief acquire a position fix
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#include "fix.hpp"

namespace system::sensors::gps {
    fix::fix([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void fix::on_start()
    {
    }
    void fix::on_execute()
    {
    }
    void fix::on_pause()
    {
    }
    void fix::on_resume()
    {
    }
    bool fix::is_finished()
    {
        return true;
    }
    etools::memory::buffer<> fix::on_complete([[maybe_unused]] etask::core::completion_reason reason)
    {
        // TODO: pack and return the task result (branch on `reason`).
        return {};
    }
} // namespace system::sensors::gps
