//! etask:doc file 0cc4adfbddf3
/**
* @file stop.hpp
*
* @brief halt the arm immediately
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#ifndef SYS_ARMS_LEFT_STOP_HPP_
#define SYS_ARMS_LEFT_STOP_HPP_
#include "../../task.hpp"
#include "context.hpp"
#include "../../../generated/scopes.hpp"
#include <etools/meta/typelist.hpp>

namespace sys::arms::left {
    //! etask:doc class f73dd2fb4502
    /**
    * @brief halt the arm immediately
    *
    * An instant_task: a fire-and-forget command. It runs to completion
    * inside the call that delivers it - the constructor is the whole task -
    * and is then destroyed. It occupies no storage, never sees an update()
    * tick, and sends no reply, so it cannot be paused, resumed, or
    * completed. See etask::core::instant_task.
    */
    //! etask:end doc class
    class stop : public instant_task {
    public:
        /**
        * @brief Construct the task from its parameters.
        *
        * @param ctx The `context` shared by this task's scope (hardware handles / state).
        */
        stop(context& ctx); //! etask:sig

        /// @brief This task's identifier on the wire.
        static constexpr global::task_id uid = global::task_id::arms_left_stop;

        /**
        * @brief The constructor's parameter types, in wire order.
        *
        * Read by the framework to unpack a request's payload into this
        * task's arguments. The order is the schema's, and it is the wire
        * contract - it is declared here because a C++17 constructor
        * signature cannot be introspected.
        *
        * Empty: this task takes no parameters.
        */
        using params = etools::meta::typelist<>;

        /**
        * @brief Accessor for the `arms.left` context this task receives.
        *
        * Supplied as the constructor's last argument when the task is
        * built from a request, where there is no call site to hand one
        * in. See `generated/scopes.hpp`.
        */
        static constexpr auto scope = &generated::scopes::arms_left;
    };
} // namespace sys::arms::left
#endif // SYS_ARMS_LEFT_STOP_HPP_
