//! etask:doc file 1a9f5f9a3597
/**
* @file stop.cpp
*
* @brief halt the arm immediately
*
* @note Generated by etask. The constructor signature (etask:sig) tracks
*       the schema and the bodies are yours. This doc block is kept in sync
*       with the schema until you edit it - after that it is yours too.
*/
//! etask:end doc file
#include "stop.hpp"

namespace sys::arms::left {
    stop::stop([[maybe_unused]] context& ctx) //! etask:sig
    {
        // TODO: initialize the task from its parameters.
    }
    void stop::on_start()
    {
    }
    void stop::on_execute()
    {
    }
    void stop::on_pause()
    {
    }
    void stop::on_resume()
    {
    }
    bool stop::is_finished()
    {
        return true;
    }
} // namespace sys::arms::left
