// SPDX-License-Identifier: MIT
/**
* @file reboot.hpp
*
* @brief reboot the controller
*
* @note Generated by etask. The constructor signature is owned by the
*       generator (tagged with the etask:sig anchor); the bodies are yours.
*/
#ifndef TASKS_REBOOT_HPP_
#define TASKS_REBOOT_HPP_
#include "task.hpp"

namespace tasks {
    class reboot : public task {
    public:
        reboot(); //! etask:sig
        void on_start() override;
        void on_execute() override;
        void on_pause() override;
        void on_resume() override;
        bool is_finished() override;

        static constexpr global::task_id uid = global::task_id::reboot;
    };
} // namespace tasks
#endif // TASKS_REBOOT_HPP_
